### ISSUE TITLE
Problems or maybe bugs?

### ISSUE THREAD

**Issue by YZhouEntheos** [FelixKrueger/TrimGalore#1]
Hi, I’m a grad student at UC-Berkeley and we had some simple problems regarding your “trim_galore". We discussed and can not Google it out, so could you please provide some information?

The script I used is just:  trim_galore --length 10 8cell.fastq

Single end small RNA data to be trimmed at 8cell stage. However, —length does not seem to work. These two prompts continue to show:
Minimum required sequence length before a sequence gets removed: 18bp
5515374 sequences processed in total
Sequences removed because they become shorter than the length cutoff of 18bp: 1417793 (25.7%)

I think it meant “—length” option does not work? 
However I was able to specify maximum trimmed length through:  trim_galore --max_length 30 8cell.fastq. 
I tried to reinstall it, and the cutadapt version, trim_galore version are newest, but neither worked.

Thanks again for your help!

**Comment by FelixKrueger** [comment]
Hi Yun,

I have now changed the code so that setting `--length` takes precedence over the small RNA minimum length of 18 bp. Can you just clone the latest development version and let me know if there still are any problems? Best, Felix

**Comment by YZhouEntheos** [comment]
Yes I think now it works well! Thanks Felix.
