### ISSUE TITLE
How to enter the Adaptor sequence manually？

### ISSUE THREAD

**Issue by Rui-Jing** [FelixKrueger/TrimGalore#100]
Hi，
Thanks for developing this user-friendly tool. I have a problem about remove adaptor from sequencing data.
Below is a schematic of my sequencing sample:
[
![image](https://user-images.githubusercontent.com/59251760/89502765-16a51400-d7f8-11ea-93fc-65998f5c5607.png)
](url)
![image](https://user-images.githubusercontent.com/59251760/89502806-26245d00-d7f8-11ea-99eb-1c80eb4fd8b1.png)
[](url)
In the sequencing sequence, the red N on behalf of the DNA sequence, others are adaptor.
So, How do I remove these adaptors with trim_galore, manually?
Looking forward to your kind reply.

**Comment by FelixKrueger** [comment]
Hi Rui,

I am currently on holiday and will only be able to take a look at this next week I am afraid. As a first step, I would run your data through FastQC. If you find that FastQC produces a line for Illumina standard adapter (typically in red), then you can just run Trim Galore in default mode (`trim_galore --paired file1 file2`) as this will just do the right thing. Else, could you attach or email me the FastQC html report to take a look myself? Thanks, Felix
