### ISSUE TITLE
Multicore support issues

### ISSUE THREAD

**Issue by dahun73** [FelixKrueger/TrimGalore#101]
Hello,

I'm using Trim_galore ususally when I'm pre-processing my all raw data.
However, today I found something wrong running trim_galore.
Multicore support is not enabled now.

![image](https://user-images.githubusercontent.com/52641420/90088315-9d5a7380-dd59-11ea-92f7-bf190598b9f5.png)
As you can see, cutadapt version is 2.10.
Trim_galore version is 0.6.5dev now.
Is there any solution about that?

**Comment by FelixKrueger** [comment]
I think enabling multicore usage requires you to specify `-j 2` or more (ideally not more than 4 as it doesn't bring much extra beyond 4). In order to work fully you will need `pigz` and Python 3 running on your system.

**Comment by dahun73** [comment]
Thank you for reply!

So, I checked my packages. I'm using 'pigz' and Python3 now. Also, our server could use 40 multi-cores now.
Actually, It didn't come out multicore support issue the day before. Yesterday, it came out suddenly...
Also, it came out multicore issue but it is working well(I don't know it work with multicore).

**Comment by FelixKrueger** [comment]
Excellent, so I think we can assume this is now all working?
