### ISSUE TITLE
issue for excessive number of cores

### ISSUE THREAD

**Issue by dahun73** [FelixKrueger/TrimGalore#104]
Hi all!!

It's really helpful using 'trimgalore'! Thank you in advance. Actually, I have a question for number of core issue.
Our server has 40 cores now. When I run trim galore, however, there is number of cores issue. 

![image](https://user-images.githubusercontent.com/52641420/93045456-31d62f80-f692-11ea-9dc8-932e377c3867.png)

Why this issue happend? Also, if I ignore this issue and run more than 8 cores, is there any problems happening?

Thanks!
Dahun

**Comment by FelixKrueger** [comment]
Hi Dahun,

According to tests we ran a while ago there doesn't seem to be any additional benefit of specifying a very high number of cores, please see these release notes for more information: https://github.com/FelixKrueger/TrimGalore/tree/0.6.0

It will probably work nevertheless.

**Comment by dahun73** [comment]
Thank you for kind explanation!

There is not huge differences from 2 to 8 cores. Then, I should use just 4 cores. :) 

Thanks!!

Dahun

**Comment by FelixKrueger** [comment]
Indeed, I think we also concluded that using 4 cores seems to be something like a sweet spot.
