### ISSUE TITLE
input file

### ISSUE THREAD

**Issue by xiannvdezhu** [FelixKrueger/TrimGalore#106]
Hi,
  An error occurred when I called the command with another program
log:
Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: '/usr/local/python3/bin/cutadapt' (user defined)
Cutadapt seems to be working fine (tested command '/usr/local/python3/bin/cutadapt --version')
Cutadapt version: 2.10
single-core operation.
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Output will be written into the directory: /root/out/
Using user-specified basename (>>2_4_L2<<) instead of deriving the filename from the input file(s)
[FATAL ERROR]: Number of files supplied can be 1 (single-end mode), or 2 (paired-end mode), but was: 4. Please respecify!
command:
/root/bin/TrimGalore-0.6.5/trim_galore --paired --path_to_cutadapt /usr/local/python3/bin/cutadapt --stringency 3 --gzip --trim-n -length 75 -o /root/out/ --no_report_file -q 30 --basename 2_4_L2 /root/source/2_4_L2_1.fq.gz /root/source/2_4_L2_2.fq.gz >> /root/out/cutadapt.log

**Comment by FelixKrueger** [comment]
The command: 

```
/root/bin/TrimGalore-0.6.5/trim_galore --paired --path_to_cutadapt /usr/local/python3/bin/cutadapt --stringency 3 --gzip --trim-n -length 75 -o /root/out/ --no_report_file -q 30 --basename 2_4_L2 /root/source/2_4_L2_1.fq.gz /root/source/2_4_L2_2.fq.gz
```

as such seems to run fine (I have just tested it with the the current version, as well as v0.6.5). The issue seems to be that you are specifying a `--basename`, and for this this you can only use a single file, or one file pair. However, you do supply the 4 arguments:  

```
/root/source/2_4_L2_1.fq.gz
/root/source/2_4_L2_2.fq.gz
>>
/root/out/cutadapt.log
```

And thus the run doesn't start. I would suggest you drop `--no_report` and the redirection, and all should be fine:

```
/root/bin/TrimGalore-0.6.5/trim_galore --paired --path_to_cutadapt /usr/local/python3/bin/cutadapt --stringency 3 --gzip --trim-n -length 75 -o /root/out/ -q 30 --basename 2_4_L2 /root/source/2_4_L2_1.fq.gz /root/source/2_4_L2_2.fq.gz
```

**Comment by xiannvdezhu** [comment]
oh!  thanks you! 
It's on!!!

**Comment by FelixKrueger** [comment]
Excellent!
