### ISSUE TITLE
Incompatibility error with latest python 3.9.0

### ISSUE THREAD

**Issue by janstrauss1** [FelixKrueger/TrimGalore#109]
Hi there,

I tried to install TrimGalore into my latest `miniconda3` environment via `bioconda` using `conda install trim-galore`.
Unfortunately, it appears to be incompatible with the latest `python 3.9.0` release. Please see the terminal output below.
I receive a similar error message when using `conda install cutadapt`.

Which `python` version would you recommend using for `TrimGalore`?

Many thanks in advance for your feedback!

Jan

```
$ conda install trim-galore
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - trim-galore -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

**Comment by janstrauss1** [comment]
> Hi there,
> 
> I tried to install TrimGalore into my latest `miniconda3` environment via `bioconda` using `conda install trim-galore`.
> Unfortunately, it appears to be incompatible with the latest `python 3.9.0` release. Please see the terminal output below.
> I receive a similar error message when using `conda install cutadapt`.
> 
> Which `python` version would you recommend using for `TrimGalore`?
> 
> Many thanks in advance for your feedback!
> 
> Jan
> 
> ```
> $ conda install trim-galore
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
>   - trim-galore -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*']
> 
> Your python: python=3.9
> 
> If python is on the left-most side of the chain, that's the version you've asked for.
> When python appears to the right, that indicates that the thing on the left is somehow
> not available for the python version you are constrained to. Note that conda will not
> change your python version to a different minor version unless you explicitly specify
> that.
> ```

**Comment by janstrauss1** [comment]
I just figured that it works well within a `python 3.8.6` environment

**Comment by FelixKrueger** [comment]
I'm glad you found a fix. I think it is really more a Conda setting, rather than something that actually affects Trim Galore or Cutadapt itself.
