### ISSUE TITLE
Error - adapter trimming

### ISSUE THREAD

**Issue by bioramg** [FelixKrueger/TrimGalore#110]
Hi,
I would like to trim adapter sequences from Illumina reads. I read manual and given the output format. But it shows an error when using the following command.

./../../anaconda3/bin/trim_galore --quality -o --/home/Illumina/  .  --path_to_cutadapt ./../../anaconda3/bin/cutadapt --paired ./../../forward_1.fastq.gz ./../../reverse_2.fastq.gz 

Thank you.

**Comment by FelixKrueger** [comment]
Hi there, what exactly is the error you are seeing? I would imagine that `--quality` requires you to specify a quality value (or if you lose this parameter the default quality will be Phred 20).

 `-o --/home/Illumina/ . ` This will certainly go wrong as well, as there is no option `--/home/illumina/`, and the stray `.` would be interpreted as the first input file, which it isn't.

**Comment by bioramg** [comment]
Thank you.

Sorry. I am a beginner in bioinformatics. Could you please give correct command to execute?

.trim_galore --quality  --/home/Illumina/ . --path_to_cutadapt /bin/cutadapt --paired input_1.fastq input_2.fastq

Is it correct?

**Comment by FelixKrueger** [comment]
`trim_galore --gzip --path_to_cutadapt /bin/cutadapt --paired input_1.fastq input_2.fastq`

A command like this might work.

**Comment by bioramg** [comment]
Thank you. I shall try and inform you. Meanwhile should I use --gzip for fastq.gz files?

**Comment by FelixKrueger** [comment]
Trim Galore detects whether input files end in `.gz`, and if so, it will set `--gzip` automatically. So you may as well not specify it explicitly.

**Comment by bioramg** [comment]
Thank you.

**Comment by aalkin2001** [comment]
Hi Felix,
I am having an issue with adapter trimming. I ran the following command:
trim_galore --illumina --phred33 --fastqc --retain_unpaired --paired K1_R1.fastq K1_R2.fastq K2_R1.fastq K2_R2.fastq W1_R1.fastq W1_R2.fastq W2_R1.fastq W2_R2.fastq -o --output_dir trimmed_fastq

Output response/Result: Please provide an even number of input files for paired-end FastQ trimming! Aborting ...
Is there anything I did wrong?
Thank you.

**Comment by FelixKrueger** [comment]
I think the last part of the command is the culprit, as `-o --output_dir trimmed_fastq`  would use `--output_dir` as the output directory, and then there is a single trailing file called `trimmed_fastq`.

I think you should be able to shorten the command to:

```
trim_galore --fastqc  --gzip --output_dir trimmed_fastq *fastq

**Comment by aalkin2001** [comment]
Thank you, Felix. The command worked.

**Comment by FelixKrueger** [comment]
Excellent! Good luck!
