### ISSUE TITLE
Adapter sequence must contain DNA characters only (A,C,T,G or N)!

### ISSUE THREAD

**Issue by titand98** [FelixKrueger/TrimGalore#111]
base) erpl@erpl-HP-Z840-Workstation:~/sayak/pilot study/downloaded_Raw_files$ trim_galore  --fastqc -a -dont_gzip o ../trimmed_files\(trial\)/ SRR1777087.1
_Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 3.1
single-core operation.
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Adapter sequence must contain DNA characters only (A,C,T,G or N)!

I have tried commenting out line 2 two lines in perl file still getting that error
  else{ # default
            #unless ($adapter =~ /^[ACTGNXactgnx]+$/){
                #die "Adapter sequence must contain DNA characters only (A,C,T,G or N)!\n";
            }    
            $adapter = uc$adapter;
        }

plz help!!!!!!!!!!!!!!!!!!

**Comment by FelixKrueger** [comment]
You command line uses `-a -dont_gzip`. Specifying `-a` overrides the adapter auto-detection, and instead tries to use `-dont_gzip` as the adapter sequence (which isn't allowed). I would also try to use weird symbols in the directory file, e.g. `()!/#` etc, as they will most likely cause trouble. The following command should work just fine:

```
trim_galore --fastqc -o ../trimmed_files/ SRR1777087.1.fastq.gz
```

**Comment by titand98** [comment]
thanks sir.issue resolved
