### ISSUE TITLE
Multicore support not enabled

### ISSUE THREAD

**Issue by dahun73** [FelixKrueger/TrimGalore#116]
Hello! 

First, thank you for using such a nice tool.

I have a problem setting TrimGalore.
Since I re-downloaded the cutadapt, fastqc and TrimGalore again, multicore is not supported now.
Umm... I;m sorry for uploading such a same problem again.

version of tools are written below.

nepi@nepi:~/Downloads$ python --version
Python 3.8.5
nepi@nepi:~/Downloads$ cutadapt --version
3.4

nepi@nepi:~/Downloads$ fastqc --version
FastQC v0.11.9

nepi@nepi:~/Downloads$ trim_galore
Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 3.4
single-core operation.
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Please provide the filename(s) of one or more FastQ file(s) to launch Trim Galore!

USAGE:  'trim_galore [options] <filename(s)>'    or    'trim_galore --help'    for more options

Also, TrimGalore version is 0.6.6. 

I tried to re-download cutadapt version to 2.8. But it didn't work... TT

+ info)

I used 4 cores using -j option but there was not error regarding multicore issue. Is it okay to keep running?
I also have one question about this notice. I download pigz package but note message always came out.
"To increase performance, please install 'pigz' and run again"
If pigz is downloaded, should I skip this notice?

**Comment by FelixKrueger** [comment]
Sorry for the late reply, I was on vacation. A couple of things: If you downloaded all the tools, and they all work, I don't see why there should be any problem. The Trim Galore message certainly looks alright, given that in the example you only ran

```
trim_galore
```

with no further options of arguments.

If you tried to install `pigz`, and you see the error message that it is not present, `pigz` is not in your `PATH`. You need to be able to run `which pigz` and see where the executable is located, if you don't see that information, simply add it to your PATH.

I believe that properly installing `pigz` will most likely solve your issues, but in any case, the run should complete just fine, but maybe take a bit longer.
