### ISSUE TITLE
Suggest updating to allow multiple treads in cutadapt (if not already?)

### ISSUE THREAD

**Issue by AMChalkie** [FelixKrueger/TrimGalore#12]
https://cutadapt.readthedocs.io/en/stable/changes.html#v1-15-2017-11-23

Cutadapt can now run on multiple CPU cores in parallel! To enable it, use the option -j N (or the long form --cores=N), where N is the number of cores to use. Multi-core support is only available on Python 3, and not yet with some command-line arguments. See the new section about multi-core in the documentation for details. When writing .gz files, make sure you have pigz installed to get the best speedup.

**Comment by FelixKrueger** [comment]
I believe this would require a fairly major re-write, and since it only currently works with specific versions of Python and options I think I might hold back until it becomes more stable and/or compatible. Sorry, Felix
