### ISSUE TITLE
primerset?

### ISSUE THREAD

**Issue by marwa38** [FelixKrueger/TrimGalore#121]
I worked with TrimGalore as I was advised by the sequencing centre for trimming all Illumina adaptors when I asked for the primer set and it works amazingly well where I used the following code:

 trim_galore -q 30 --phred33 --paired --gzip --fastqc --fastqc_args "--nogroup" -o ./Trimmed-TrimGalore --length 20 --stringency 1 -e 0 --clip_R1 17 --clip_R2 21 *_S"$i"_L001_R1_001.fastq *_S"$i"_L001_R2_001.fastq

Currently, I am using snakemake which requires me to add the primer sequences to be trimmed, could you please share with me the primer set used as default in trim galore?

The details of the sequencer and protocol are as follows:
Miseq sequencer, flowcells :v3 600c 2x300
NextraXT V2 was used set A, B and D.

Thanks 
Marwa

**Comment by FelixKrueger** [comment]
Hi Marwa,

apologies for the late response, I've been out all day.

Trim Galore attempts to auto-detect the adapter sequence used, and it tries to find one of either the Illumina standard, Nextera or small RNA adapter. The adapter found to be present most will be printed to the trimming report, so you can just take a look there which adapter was detected and removed.

If you know exactly what you are dealing with you can also specify the adapter sequence manually, and choose one of the following three:

```
--illumina              Adapter sequence to be trimmed is the first 13bp of the Illumina universal adapter
                        'AGATCGGAAGAGC' instead of the default auto-detection of adapter sequence.

--nextera               Adapter sequence to be trimmed is the first 12bp of the Nextera adapter
                        'CTGTCTCTTATA' instead of the default auto-detection of adapter sequence.

--small_rna             Adapter sequence to be trimmed is the first 12bp of the Illumina Small RNA 3' Adapter
                        'TGGAATTCTCGG' instead of the default auto-detection of adapter sequence. Selecting
                        to trim smallRNA adapters will also lower the --length value to 18bp. If the smallRNA
                        libraries are paired-end then a2 will be set to the Illumina small RNA 5' adapter
                        automatically (GATCGTCGGACT) unless -a 2 had been defined explicitly.
```

I hope this helps?

**Comment by FelixKrueger** [comment]
I hope this cleared things up?
