### ISSUE TITLE
FastQC location as argument to trim_galore

### ISSUE THREAD

**Issue by niekwit** [FelixKrueger/TrimGalore#122]
Is it possible to parse the FastQC directory to trim_galore if it is not set in $PATH? Thank you.

**Comment by FelixKrueger** [comment]
I think you can't pass it as an argument, but you can just modify this line in `trim_galore` to paste in the full path to the FastQC executable:

https://github.com/FelixKrueger/TrimGalore/blob/eb0480424b36fb22027e351869c669b8dc77335b/trim_galore#L456

**Comment by niekwit** [comment]
Thank you, that will help me out.
