### ISSUE TITLE
cutadapt cores option docs are misleading

### ISSUE THREAD

**Issue by keiranmraine** [FelixKrueger/TrimGalore#123]
Hi,

The cli docs indicate:

> -j/--cores INT          Number of cores to be used for trimming [default: 1]. For Cutadapt to work with multiple cores, it
                        requires Python 3 as well as parallel gzip (pigz) installed on the system. The version of Python used 
                        is detected from the shebang line of the Cutadapt executable (either 'cutadapt', or a specified path).
                        If Python 2 is detected, --cores is set to 1.

This doesn't appear to match the code as that specifically looks at the version of the actual tool, not python itself:

https://github.com/FelixKrueger/TrimGalore/blob/eb0480424b36fb22027e351869c669b8dc77335b/trim_galore#L783-L819

It looks like the reading of the `#!` was stopped ~3 years ago.

**Comment by FelixKrueger** [comment]
Thanks for spotting this, I have now changed the text for `--help` and in the User Guide to reflect this (at least to some extent),  (811f364261e48898672505a9a5ee439353532c07).
