### ISSUE TITLE
The --nextseq argument doesn't change the parameters of cutadapt

### ISSUE THREAD

**Issue by josephhughes** [FelixKrueger/TrimGalore#125]
I'm using the following command in trim_galore:

`trim_galore --nextseq 20 --dont_gzip --length 50 --paired $fq1 $fq2`

and I was expecting this to be reflected in the trim_report.txt with `-nextseq-trim=3'CUTOFF` but I just get:

`-j 1 -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC `

which is the same as when I specify the following in trim_galore:

`trim_galore -q 20 --dont_gzip --length 50 --paired $fq1 $fq2`

Have I misunderstood what `--nextseq` does or am I mis-specifying something?

**Comment by FelixKrueger** [comment]
This is very odd, I have just run a few tests with and w/o `--dont_gzip`, and I consistently get:

```
trim_galore --dont --paired --length 50 test_R1.fastq test_R2.fastq
```

```
>>> Now performing quality (cutoff '-q 20') and adapter trimming in a single pass for the adapter sequence: 'TGGAATTCTCGG' from file test_R1.fastq <<<
This is cutadapt 3.5 with Python 3.9.7
Command line parameters: -j 1 -e 0.1 -q 20 -O 1 -a TGGAATTCTCGG test_R1.fastq
```


or 

```
trim_galore --dont --nextseq 20 --paired --length 50 test_R1.fastq test_R2.fastq`
```

 ```
>>> Now performing quality (cutoff '--nextseq-trim=20') and adapter trimming in a single pass for the adapter sequence: 'TGGAATTCTCGG' from file test_R1.fastq <<<
This is cutadapt 3.5 with Python 3.9.7
Command line parameters: -j 1 -e 0.1 --nextseq-trim=20 -O 1 -a TGGAATTCTCGG test_R1.fastq
```

Which version of Trim Galore are you using?

**Comment by josephhughes** [comment]
Really sorry. My Friday mistake :(.

**Comment by FelixKrueger** [comment]
No worries, glad it got resolved! Have a good weekend!
