### ISSUE TITLE
passing arguments to cutadapt

### ISSUE THREAD

**Issue by samuelCollombet** [FelixKrueger/TrimGalore#13]
Hi,
Sorry if this is not the best place to write that...
It seems that there is no possibility in Trim_galore to pass arguments to cutapadt, am I right? 
Would it be possible to add this option? The main reason I am asking that is because the latest version of cutadapt as an option to be multi-threaded, and it would be great to be able to use it when using trim_galore to speed up a bit the process :)

Many thanks!

**Comment by FelixKrueger** [comment]
Hi Samuel,
This has actually been asked last week already, but I believe this would probably be a fairly major rewrite. I might reconsider if the multicore option becomes a more permanent feature of Cutadapt. Please also see here: https://github.com/FelixKrueger/TrimGalore/issues/12

**Comment by samuelCollombet** [comment]
Oops sorry I didn't check closed issues. Thanks for the answer! Would be a
great feature, let's see how it goes with cutadapt :)
Best,
samuel
