### ISSUE TITLE
TrimGalored sequence cannot be mapped with Bowtie2

### ISSUE THREAD

**Issue by moqri** [FelixKrueger/TrimGalore#135]
When I use TrimGalore, some of my trimmed files cannot be mapped using Bowtie2.

Example: SRR11908644 raw data trimmed using TrimGalore then fed into Bowtie2 results in:
```
Saw ASCII character 10 but expected 33-based Phred qual.
terminate called after throwing an instance of 'int'
Saw ASCII character (ERR): bowtie2-align died with signal 6 (ABRT)
```
Any suggestions?

**Comment by FelixKrueger** [comment]
This is very strange, but I doubt it has anything to do with Trim Galore to be honest. Can you run FastQC on the file without any issues?

**Comment by FelixKrueger** [comment]
Haven't heard back in a long time.
