### ISSUE TITLE
equivalent of `--discard-untrimmed` parameter in `trim_galore`

### ISSUE THREAD

**Issue by bounlu** [FelixKrueger/TrimGalore#138]
What is the equivalent of `--discard-untrimmed` parameter in `trim_galore`? How can I discard the reads without the adapter sequence from the output for the downstream analyses?

**cutadapt:**
```
  --discard-untrimmed, --trimmed-only
                        Discard reads that do not contain an adapter.
```

**Comment by FelixKrueger** [comment]
I don't think there currently is an option to discard reads without an adapter sequence. I suppose as a little 'hack' you could set `-q 0` to skip quality trimming, and set `--max_length (readlength) - 1`. In theory this should do the same thing.
