### ISSUE TITLE
cutadapt: error: unrecognized arguments: -f P2_A01_M_0001.fastq Cutadapt terminated with exit signal: '512'.

### ISSUE THREAD

**Issue by sevmurdock** [FelixKrueger/TrimGalore#141]
I keep getting the same error messages cutadapt: error: unrecognized arguments: -f P2_A01_M_0001.fastq 
Cutadapt terminated with exit signal: '512'.

This is my origional code 
trim_galore -q 30 --phred33 --gzip --length 36 --fastqc P2_A01_M_0001.fastq -o trimmed_reads_P2

I even tried just running trim_galore  P2_A01_M_0001.fastq -o trimmed_reads_P2 and I am still getting the same error messages. 

Run information shown below ....

Minimum required sequence length before a sequence gets removed: 36 bp
Running FastQC on the data once trimming has completed
Output file(s) will be GZIP compressed

Writing final adapter and quality trimmed output to P2_A01_M_0001_trimmed.fq.gz

  >>> Now performing quality (cutoff 30) and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file P2_A01_M_0001.fastq <<< 
This is cutadapt 4.1 with Python 3.10.5
Command line parameters: -f fastq -e 0.1 -q 30 -O 1 -a AGATCGGAAGAGC P2_A01_M_0001.fastq
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: unrecognized arguments: -f P2_A01_M_0001.fastq

Cutadapt terminated with exit signal: '512'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

**Comment by FelixKrueger** [comment]
This is very odd indeed, since at no point in your command line I can see the option `-f P2_A01_M_0001.fastq`. 

I just copied your command but changed the input file to a test file that ships with Trim Galore:
```
trim_galore -q 30 --phred33 --gzip --length 36 --fastqc illumina_10K.fastq.gz -o trimmed_reads_P2
```

And it completes just fine. My guess would be that something is wrong with `--fastqc`, maybe you copy-pasted it from a PDF document or something similar where there might be invisible characters somewhere? I would suggest typing the command once more from scratch, and see if the issue is still there....

**Comment by sevmurdock** [comment]
Thanks !! I will give that a try!!

**Comment by cbcptdtptp** [comment]
Hey, I met exactly the same problem and found that it was because the version 4.1 of cutadapt is not accepted by trim_galore. I installed cutadapt 1.18 and the problem is solved.

**Comment by sevmurdock** [comment]
Thanks for letting me know. Oddly enough, I think I ran conda update
Trim-galore and the problem went away. I will keep this in the back of my
mind for my next round of samples that come in.

Warm regards,
Savanna
