### ISSUE TITLE
TrimGalore says adapters are removed, but FastQC says there were never any to begin with

### ISSUE THREAD

**Issue by hhg7** [FelixKrueger/TrimGalore#15]
Hello,
I am running FastQC before and after some single-end data, running trimgalore with no options.  For some reason, FastQC says there are no adapters in either the raw or the trimmed fastq files.  However, TrimGalore says it is removing the adapters.  Perhaps FastQC isn't programmed with all adapters that TrimGalore is?

**Comment by FelixKrueger** [comment]
Hi @hhg7,

Trim Galore is using the same adapter sequences that FastQC is, however FastQC only registers them as adapter contamination if the entire sequence length (some 12 or 13 bp) is found in full. The adapter trimming within Trim Galore does however also remove trailing bases from reads that *look* like adapter. These bases might be innocent genomic bases, but they might as well be the start of a read-through adapter contamination. As an example, take the start of the Illumina adapter `AGATC...`. If sequences end in:

```
NNNNNNA
NNNNNAG
NNNNAGA
NNNAGAT
NNAGATC
```

The result would be:

```
NNNNNN
NNNNN
NNNN
NNN
NN
```

If you look at the trimming histogram in the trimming report you should see that 1 bp gets removed very often (basically any sequence ending in `A`), then sequences ending in `AG` and so on. There should be a very steep drop from 1 to 2 to 3 etc bp (around an order of magnitude or so). If you had highly adapter contaminated library you see that bases are being trimmed of ranging from few to many (e.g. 90bp) with very high counts at each position. In your case I suspect that you are more likely to see numbers like so:

```
bp trimmed  //  #
1     //  1000000
2     //   300000
3     //    40000
4     //     8000
...
```
 I hope this helps! Felix

**Comment by hhg7** [comment]
hi Felix,

yes this helps.  Is there a list of adapters that TrimGalore searches for?

As I search the source code, I see, 

AGATCGGAAGAGC
CTGTCTCTTATA
GATCGTCGGACT
TGGAATTCTCGG

is this it?

**Comment by FelixKrueger** [comment]
In fact it only looks for `AGATCGGAAGAGC` (Illumina), `CTGTCTCTTATA` (Nextera) or `TGGAATTCTCGG` (small RNA). If small RNA is detected in a paired end setting, `GATCGTCGGACT` is set as -a2. I'm afraid it Trim Galore doesn't look in specific lists like the ones you can specify for Cutadapt or Trimmomatic, mainly because in our experience this is almost never what you actually want to do. 

Most of the times when people want to specify several different adapters with `-a` they want to supply adapters with different barcodes, or they want to supply the (incorrect) reverse complemented sequence. In close to all cases it is enough to use the generic Illumina/iTag sequence `AGATCGGAAGAGC`. I am happy to look at what you actually want to do, maybe you've got a special application that really requires different sequences? Cheers, Felix

**Comment by dcassol** [comment]
Hello,
I think I'm having the opposite problem.
I am running FastQC before and after trimGalore analysis. However, I continue to observe adapters after the analysis.
I am running:
trim_galore -q 20 --phred33 -a GTGTCAGTCACTTCCAGCGG --length 20 -o /myFolder/ /myFile.fq

BEFORE:
![image](https://user-images.githubusercontent.com/12722576/35938676-b890293a-0bfe-11e8-8755-9e54be4e4634.png)

AFTER:
![image](https://user-images.githubusercontent.com/12722576/35939531-4318067a-0c01-11e8-9278-1f79818a70ec.png)

**Comment by FelixKrueger** [comment]
Hmm, may I ask what the sequence `GTGTCAGTCACTTCCAGCGG` is? FastQC indicates that the sample contains the standard Illumina adapter, so trimming with the command:

`trim_galore -o /myFolder/ /myFile.fq` 

should do exactly what you want it to do, because it would auto-detect the Illumina adapter sequence `AGATCGGAAGAGC`.

**Comment by FelixKrueger** [comment]
If you look at the trimming report, does it get removed much? Normally both Read 1 and Read 2 read into a sequence that starts with `AGATCGGAAGAGC`, which is exactly what FastQC is detecting. If I were you I would try running Trim Galore in default mode (my command above) and then compare the trimming reports. This should convince you that the default behaviour is the one you need in your situation. Cheers, Felix

**Comment by dcassol** [comment]
Yes, you are right!
I was trying to compare my results from FASTX-Toolkit, and when I ran this:
fastx_clipper -Q 33 -a GTGTCAGTCACTTCCAGCGG -l 20 -i myfile.fq -o myFile_clipped.fq
The adapters have been completely removed.
Do you have an idea why this happens (excuse my silly question)?

**Comment by FelixKrueger** [comment]
Hmm, I don't think I have an answer to that I think. What you could do is to add the sequence `GTGTCAGTCACTTCCAGCGG` to the adapters.txt file in the FastQC configuration and run FastQC again. This would then add a new line to the adapter contamination plot that might show you whether that sequences is highly present in your files.

**Comment by snijesh** [comment]
> Trim Galore is using the same adapter sequences that FastQC is, however FastQC only registers them as adapter contamination if the entire sequence length (some 12 or 13 bp) is found in full. The adapter trimming within Trim Galore does however also remove trailing bases from reads that _look_ like adapter. These bases might be innocent genomic bases, but they might as well be the start of a read-through adapter contamination. As an example, take the start of the Illumina adapter `AGATC...`. If sequences end in:
> 
> ```
> NNNNNNA
> NNNNNAG
> NNNNAGA
> NNNAGAT
> NNAGATC
> ```
> 
> The result would be:
> 
> ```
> NNNNNN
> NNNNN
> NNNN
> NNN
> NN
> ```


Are there any options to keep the reads when they are not adaptoers?

**Comment by FelixKrueger** [comment]
You mean only keep reads for which nothing had been trimmed? I suppose you could `--length` for that, and set it to your starting maximum read length.

You could also increase the `--stringency` which regulates how much overlap with an adapter a sequence has to have before getting removed.
