### ISSUE TITLE
files corrupted after using clock command

### ISSUE THREAD

**Issue by AnastasijaVasilevska** [FelixKrueger/TrimGalore#161]
Hello,

I am trying to trim the sequences I have using the clock command on fastq files. This is the command I used: 'trim_galore --clock --paired filename_R1 filename_R2'. The command successfully runs and I get the two output files *.clock_UMI.R1.fq and *.clock_UMI.R2.fq, but the data in the files is corrupted. 

I checked the files before using clock and everything is alright with the original files, but when I look at the clock files, some sequences are okay, but some are all over the place (part of the DNA sequence in the ID, different length of sequence and quality, the DNA sequence split into three lines instead of one, etc)

I tried searching for a solution but I couldn't find anything, so I was wondering if you have any idea what the issue might be?

**Comment by FelixKrueger** [comment]
that is very odd indeed. The only thing that could mess up samples like this is normally file endings. Would you be able to share a subset of your input files with me to take a look?

You could also uncompress your files (e.g. `gunzip *files`), and then run `file file_R1.fastq` on it. This might reveal if there are weird file endings. If something happened to the file you could try `dos2unix` or `mac2unix`  on the files to see if that helps?

**Comment by FelixKrueger** [comment]
Good to hear that it's OK now, did you figure out what the issue was?
