### ISSUE TITLE
Add trimmed sequences to fastq header?

### ISSUE THREAD

**Issue by js72587** [FelixKrueger/TrimGalore#166]
Is there a way to add the trimmed sequences (--clip_R1, --three_prime_clip_R1, etc.) to the fastq headers? It seems cutadapt has the `--rename` parameter to do this, but it doesn't look like TrimGalore has this option; is my understanding correct?

Thank you!

**Comment by FelixKrueger** [comment]
It doesn't have the this option right now, but it shouldn't be overly complicated to add (at least not for `--clip_r1, --three_prime_clip_r1 and so on`).

**Comment by js72587** [comment]
Thank you!

**Comment by js72587** [comment]
Thank you! That'd be great.

**Comment by FelixKrueger** [comment]
If I were to give this a go, what would you like to see? I could imagine something like:

if `--clip_r1` or `--clip_r2` is 1 or greater, we could add something like this to the header (here for `--clip_r1 4`:

```bash
:clip5:GATC
```

if `--three_prime_clip_r1` or `--three_prime_clip_r2` is 1 or greater, we could add something like this to the header (here for `--three_prime_clip_r1 6`:

```bash
:clip3:TAAATC
```

Or, if both 5' and 3' clipping were selected, add both like so:

```bash
:clip5:GATC:clip3:TAAATC
```

Does this sound useful?

**Comment by js72587** [comment]
Yes, that would be exactly what we're looking for. Thanks a lot!

**Comment by FelixKrueger** [comment]
Hi again. I have just added a new option `--rename` that should do exactly what outlined above. I have tried to make it work in single-end as well as paired-end mode (for use with `--rrbs` or `--polyA`). 
it should work for 5'-clipping (`--clip_(r1/r2)`) and 3'-clipping (`--three_prime_clip_(r1/r2)`), and combinations thereof. Furthermore, it should also work with `--hardtrim5` and `--hardtrim3`, and hopefully help help with UMI handling.

Can you please clone the dev version, and let me know if it works in your hands?

**Comment by js72587** [comment]
Thanks so much for implementing this so quickly! I'll test it and will be back with feedback later this week. Really appreciated!

**Comment by js72587** [comment]
Hi Felix, I tested this and it works perfectly. Thank you so much!

**Comment by FelixKrueger** [comment]
Fantastic. It will find its way into the next release then. All the best!
