### ISSUE TITLE
Trim-galore through Bioconda requires workaround for M1 Macs.

### ISSUE THREAD

**Issue by trev-f** [FelixKrueger/TrimGalore#168]
Installing cutadapt on an M1 Mac requires a workaround as [documented in cutadapt's issues](https://github.com/marcelm/cutadapt/issues/672#issuecomment-1539272348). Installing trim galore on an M1 Mac required a similar workaround for me:

```
CONDA_SUBDIR=osx-64 conda create -n trimgalore -c bioconda -c conda-forge trim-galore=0.6.10
```

I am not sure if explicitly supplying channel names and trim galore version is required, but this command works.

**Comment by FelixKrueger** [comment]
Many thanks for mentioning and cross-referencing this here!
