### ISSUE TITLE
Conda installation of trim_galore uses really old version of cutadapt

### ISSUE THREAD

**Issue by vkkodali** [FelixKrueger/TrimGalore#172]
Installing `trim_galore` using conda installs v1.18 of `cutadapt` when the latest version is 4.4:
```
cutadapt           bioconda/linux-64::cutadapt-1.18-py37h14c3975_1
```
Can you please update the conda recipe to install a more up-to-date version of `cutadapt`?

**Comment by FelixKrueger** [comment]
As far as I can see the version of Cutadapt has nothing to do with the Trim Galore recipe on bioconda:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/trim-galore/meta.yaml

Indeed, when running `mamba install trim-galore` into a brand new environment I just got the following:

```
trim_galore: version 0.6.10
...
Cutadapt version: 4.4
single-core operation.
igzip command line interface 2.30.0
igzip detected. Using igzip for decompressing
```

What did you do?

**Comment by vkkodali** [comment]
Thanks, apparently the conda installation on our work machines is ancient (4.8.2). That's the reason why it was defaulting to an older version of `cutadapt`. I was able to fix it by using the latest version of `miniconda`.
