### ISSUE TITLE
Validation fails when FASTA files used as input

### ISSUE THREAD

**Issue by vkkodali** [FelixKrueger/TrimGalore#173]
I am running `trim_galore` on paired-end FASTA files. Everything works as expected except the last step of validation, which fails with the error: 
```
Input file doesn't seem to be in FastQ format at sequence 1
```
Can I explicitly tell `trim_galore` that the input files are in FASTA format and the validation step should not expect them to be FASTQ files?

**Comment by FelixKrueger** [comment]
I am afraid Trim Galore is designed for FastQ files only, if you want to trim FastA files you could probably use [Cutadapt](https://cutadapt.readthedocs.io/en/stable/) directly.

**Comment by vkkodali** [comment]
Would it be possible to add an option to disable validation?

**Comment by FelixKrueger** [comment]
You probably could find this line in `trim_galore` and comment it out...:
https://github.com/FelixKrueger/TrimGalore/blob/4edff97d22f3837d42a29e4afbfaeb6e07ffb11b/trim_galore#L1546

Alternatively, you could also fake qualities and do a FastA > FastQ conversion? Just found this link...
https://bioinformatics.stackexchange.com/questions/11192/convert-fasta-to-fastq-with-dummy-quality-scores#:~:text=The%20first%20tool%2C%20to_fake_qual%20%2C%20creates,these%20into%20a%20fastq%20file.

**Comment by vkkodali** [comment]
> You probably could find this line in `trim_galore` and comment it out...:

Thanks, I will give that a try.
