### ISSUE TITLE
TrimGalore Citation

### ISSUE THREAD

**Issue by Leo-ccc** [FelixKrueger/TrimGalore#175]
Hi!

Very brilliant tool! Really help me a lot😄👍

In addition to citing the GitHub URL directly, have the citations been updated in 2023? I didn't find any information.

Best regards.

**Comment by FelixKrueger** [comment]
Citing the Github URL is probably still a good way, but I think you can also have a citation with DOI over at Zenodo: https://zenodo.org/record/7598955 if you prefer. Thanks!
