### ISSUE TITLE
cutadapt switched to multicore

### ISSUE THREAD

**Issue by lorbaer** [FelixKrueger/TrimGalore#18]
Dear Felix,
in version 1.15 cutadapt switched to multicore and will get this as default in one of the next updates. 

Will the use of multicore (and therefore pigz) be supported in TrimGalore. Could you may give us an option to select number of cores?

cheers

**Comment by lorbaer** [comment]
arg.. ssen your answear in the closed issues..

**Comment by FelixKrueger** [comment]
I'm glad you found it, maybe it'll be added at some point...
