### ISSUE TITLE
md5sum

### ISSUE THREAD

**Issue by zhangqc723** [FelixKrueger/TrimGalore#182]
I run TrimGalore twice as follow code,
trim_galore \
    --cores 8 --quality 20 --stringency 3 \
    --paired --phred33 \
    --output_dir /test \
    R1.fq.gz R2.fq.gz
And I view the md5 value of output  from same R1 and R2 file, but the value is different.
Could you tell me why? Thanks!

**Comment by FelixKrueger** [comment]
My guess is that this has to do with the `gzip` compression, together with the`--cores 8`. If trimmed sequences get reported in a different order due to multi-core processing, the compressed files do not necessarily have the same file size.
