### ISSUE TITLE
ask for help in removing the first 10 nt random barcode in the 5’ end

### ISSUE THREAD

**Issue by Shuixin-Li** [FelixKrueger/TrimGalore#188]
Hi~ Thank you for building such amazing tool! But I am not very clear about how to achieve my goal even after reading the --help document. Could you please help me out there? 

I want to repeat some steps in a paper where describe "Raw sequencing reads produced from m1A-MAP were firstly subjected to Trim_galore (http://www.bioinformatics.babraham.ac.uk/projects/trim_galore/) for quality control and adaptor trimming. " And there are two steps: 

(1)The minimum quality threshold was set to 20, and the minimum length required for reads after trimming was 30 nt. 

(2)The remaining reads were further processed by removing the first 10 nt random barcode in the 5’ end.

I've done the first part by `trim_galore test_Input.fastq.gz test-_IP.fastq.gz test+_IP.fastq.gz --quality 20 --length 30 `

But I don't know how to achieve the second part by using Trim_galore (or it actually cannot be achieved by Trim_galore?)

For more information, the sequencing data were from Illumina. The protocal of the experiment steps are in the attachment. (But I don't have a good understanding of things in wet lab, so .. just put it here incase you need !)
[mmc7.pdf](https://github.com/FelixKrueger/TrimGalore/files/14783388/mmc7.pdf)

Thank you in advance.

**Comment by FelixKrueger** [comment]
Hi there, 

this should be really easy to achieve. Quality of 20 is the default, so you don't need to specify it explicitly; clipping 10bp from the  5' end can be clipped (after the quality and adapter removal) using `--clip_r1 10`. So your command could simply be:

```
trim_galore --length 30 --clip_r1 10 *fastq.gz
```
