### ISSUE TITLE
Trim Galore -a "A{10}"

### ISSUE THREAD

**Issue by xie186** [FelixKrueger/TrimGalore#19]
Hi Felix,

It seemed that TrimGalore is not happy with parameter setting like `-a "A{10}"`  (http://cutadapt.readthedocs.io/en/stable/recipes.html). Could you please tell me the reason? And is it possible to update this? Thanks. 

Best,
Shaojun

**Comment by FelixKrueger** [comment]
Hi Shaojun,

While Trim Galore uses Cutadapt for the trimming part it is not actually the same. It would be an easy thing to add though so I might do it anyways. Until that has happened please just use `-a AAAAAAAAAA` for the time being.

**Comment by xie186** [comment]
Got it. Thanks for developing this nice tool.

**Comment by FelixKrueger** [comment]
This should now be working, added in b1e0d7c723e5949507968cc3325f184f8aa680de. Cheers, Felix
