### ISSUE TITLE
Queries regarding TrimGalore

### ISSUE THREAD

**Issue by unikill066** [FelixKrueger/TrimGalore#191]
I usually have paired-end sequencing data, and I intend to run `trim_galore` on the example files below:

```
121_1_L001_R1_001.fastq.gz
121_2_L001_R1_001.fastq.gz
121_3_L001_R1_001.fastq.gz
121_4_L001_R1_001.fastq.gz
121_1_L001_R2_001.fastq.gz
121_2_L001_R2_001.fastq.gz
121_3_L001_R2_001.fastq.gz
121_4_L001_R2_001.fastq.gz
```
I am attempting to execute `trim_galore` on all these samples using the following commands:

```
trim_galore --paired --cores 4 121_1_L001_R1_001.fastq.gz 121_1_L001_R2_001.fastq.gz
trim_galore --paired --cores 4 121_2_L001_R1_001.fastq.gz 121_2_L001_R2_001.fastq.gz
trim_galore --paired --cores 4 121_3_L001_R1_001.fastq.gz 121_3_L001_R2_001.fastq.gz
trim_galore --paired --cores 4 121_4_L001_R1_001.fastq.gz 121_4_L001_R2_001.fastq.gz
```

Here are my queries:
Is there an efficient method to run all the fastq files at once with a single command, or do I need to use a script?
Additionally, when executing `trim_galore`, I aim to prevent the `_val_1` and `_val_2` prefixes from being appended to the newly generated fq.gz files.

**Comment by FelixKrueger** [comment]
I am sure there is some command line magic that would allow you to run things more efficiently, you should be able to find solutions by some googling or asking ChatGPT.

Here are a few thoughts:

- are your samples biological 4 replicates of the same sample/condition, or are they 4 technical replicates? In the latter case, you might want to merge all R1 and all R2 files, and then only use a single trimming command.

- in case you need to run these 4 jobs, some bash scripting might also achieve the same results. Here is a slight modification of something I have run in the past:
```bash
ls | sed s/R._001.fastq.gz$// | sort | uniq | xargs -P4 -I PREFIX bash -c 'trim_galore --paired --cores 4  PREFIXR1* PREFIXR2*'
```

This command should run 4 processes in parallel. The piped string (unique portion of the filename) is used as PREFIX, and is substituted whenever it is seen in the following command. Using another instance of `bash -c` to allow * expansion.

- the `_val_` extension is always added as a matter of course, you can use a single command afterwards to batch rename files afterwards.

**Comment by unikill066** [comment]
Thank you, @FelixKrueger. I wonder if there is a flag available for not adding any extensions such as `_val_`. However, if there isn't, that's fine—I can rename then files accordingly.

**Comment by FelixKrueger** [comment]
Just to confirm, there is no flag to not add the _val_, so `rename s/_val_/_/` will have to do. All the best!
