### ISSUE TITLE
1-8 % of PolyA always remains in the R1 of my RRBS trimed PE files

### ISSUE THREAD

**Issue by Muhyees** [FelixKrueger/TrimGalore#194]
Dear Felix,

I am using trim-galore for the trimming RRBS data with the "--rrbs --non_directional --paired --length 15 --fastqc" options, However the R1 fastqc results  of all the trimmed 34 samples showed a polyA of around 8% max.
Also, some of the Parameters shows a an error, although i was not suprised due to the nature of samples being bisulfite treated.

R1 fastqc output
![Screenshot 2024-07-28 120321](https://github.com/user-attachments/assets/4db9312d-e7ee-4ba0-afb5-e3425a86cfec)

R2 fastqc output 
![Screenshot 2024-07-28 120516](https://github.com/user-attachments/assets/2b851c47-2527-4c3c-95e0-24217c7773a5)

I will be using bismark for the alignment, but i am a bit worried if the files can be used as they are or further trimming is required to eliminate the polyA warning.

Thanks

Muazu

**Comment by FelixKrueger** [comment]
This kind of PolyA probably has to do with the library preparation, this isn't exactly common for bisulfite-seq more generally.

I suppose you've got the option to simply ignore it, chances are that sequences consisting of mainly PolyA will not result in valid alignments anyway (so in effect they will get filtered out by the alignment step itself). You could also choose to remove it, either by a second round of trimming, or by specifying 2 adapters at the same time, e.g. with `-a " AGATCGGAAGAGC -a  AAAAAAAAAAAAAAAA -n 2".

**Comment by Muhyees** [comment]
Thank you for your reply.

Indeed doing a second round of trimming has corrected the PolyA. I will compare the bismark outputs of the first and second trimming to see if it makes any difference.

Thank you.
