### ISSUE TITLE
support BGISEQ/DNBSEQ/MGISEQ?

### ISSUE THREAD

**Issue by orangeSi** [FelixKrueger/TrimGalore#196]
Hello, Do ```TrimGalore``` support  auto filter adapter for ```BGISEQ/DNBSEQ/MGISEQ``` read yet?   The adapter  sequence is at https://github.com/OpenGene/fastp/issues/259

Thanks~
Si

**Comment by FelixKrueger** [comment]
Would you be able to send me a small-ish test dataset (e.g. 100K reads) so I can take a look?

**Comment by FelixKrueger** [comment]
Hmm, I downloaded the entire dataset and added the following adapter sequences to the adapter file of FastQC:

```
AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA  MGI/BGI forward
AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG   MGI/BGI reverse
AAGTCGGA    MGI/BGI universal
```
<img width="962" alt="Screenshot 2024-10-16 at 13 43 17" src="https://github.com/user-attachments/assets/706283a5-642b-40f7-a8e1-bb3315f5a198">

It doesn't look like this is a good example of 'contamination' with the MGI/BGI adapter (the universal sequence is just about visible at the end but it also is only 8bp long...).

**Comment by orangeSi** [comment]
the result of fastqc is weird, beacuase I checked the r1 fq file by just ```zgrep``` the forward adapter got  match as this:
![image](https://github.com/user-attachments/assets/d32f21e5-96e4-4593-aab1-87921423aba6)

**Comment by FelixKrueger** [comment]
Can you include a `-c` to count how many times it is found in total? Maybe it is just so low that it doesn't show up in a  % plot?

**Comment by orangeSi** [comment]
can you extract only the 162 pair of read to fq files to do ```fastqc```, if fastqc result  show100% adapter will be normal ~

**Comment by FelixKrueger** [comment]
that works:

```
zgrep -A 2 -B 1 AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA SRR28167102.DNBSEQ-G400.r1.fq.gz | grep -v "^-" > hits.fastq
```
<img width="925" alt="Screenshot 2024-10-18 at 09 56 16" src="https://github.com/user-attachments/assets/bbe03af2-0f71-47a6-96c4-7a73f78f4719">


This is the plot for the Read 2 adapter (80 sequences):

<img width="944" alt="Screenshot 2024-10-18 at 09 58 56" src="https://github.com/user-attachments/assets/e4c3b6c1-60b8-4a40-8f04-814fc10e1fd3">

I suppose adding a flag `--bgiseq` wouldn't be too difficult. If this type of sequencing becomes more common, we could also add it to the auto-detection.

**Comment by orangeSi** [comment]
```--bgiseq``` is ok for now.

**Comment by FelixKrueger** [comment]
The option `--bgiseq` is now available from the `dev` branch. Can you let me know if it works as expected for you? If yes, it will be part of the next release.

**Comment by borgessbarbara** [comment]
Hi!
I have installed trimgalore with mamba, but the option --bgiseq is not even appearing as an option when i do trim_galore --help. When I try to run with it, it raises the error:

Unknown option: bgiseq
Please respecify command line options

This was my command:

trim_galore -q 30 --bgiseq --gzip -o trimgalore --basename filt_ --paired file_1.fastq file_2.fastq

**Comment by FelixKrueger** [comment]
As is pointed out this is currently still in the development branch and hasn't made it into a release just yet, hence why it is not available via a mamba install.

You can still clone the tool, switch to the dev branch, and then start using it. It should be something like this:

```
git clone git@github.com:FelixKrueger/TrimGalore.git
cd TrimGalore
git checkout dev
```

Good luck!

**Comment by orangeSi** [comment]
> The option `--bgiseq` is now available from the `dev` branch. Can you let me know if it works as expected for you? If yes, it will be part of the next release.

@FelixKrueger sorry, I see your comment just now. @borgessbarbara  could you help me test the dev branch with your dataset ? thanks~
