### ISSUE TITLE
Testing best practices

### ISSUE THREAD

**Issue by ionox0** [FelixKrueger/TrimGalore#23]
Thank you for your work on this project,

I was wondering if you had any suggestions for testing TrimGalore in a pipeline. For example, with a very small pair of fastqs, say only a few reads, are there any parameters or suggestions that would make a TrimGalore run only take a few seconds? Thank you

**Comment by FelixKrueger** [comment]
Hi there, I just tested the command:

`time trim_galore illumina_10K.fastq.gz` 

on 10,000 sequences and it completed in 8.017 seconds. You could probably down-sample the file (which is supplied in the folder test_files) even further, or take out sleep statements which are meant to allow you to quickly review what is actually going to be run. Is this acceptably quick? Cheers, Felix

**Comment by FelixKrueger** [comment]
Hi Ian,

I just applied some time-related reporting optimisation (a351581ab39cae817619d86903a584efc9b972b0) :smiley_cat:  which means that you should see a speed-up of up 70%* (* for very small datasets like the 10,000 sequence file mentioned above ...). Just get the latest development version for this. All the best, Felix

**Comment by FelixKrueger** [comment]
You should definitely upgrade to the latest version, as you are nearly 6 years and 20 releases behind! There is also a very high chance that the latest error you are seeing has been fixed in the meantime....
