### ISSUE TITLE
option --length might not working got v0.4.5_dev

### ISSUE THREAD

**Issue by lufuhao** [FelixKrueger/TrimGalore#24]
hi, I used "--length 70" for mate pairs, but still many reads shorter than 70 go to final output.

Would you please double check?

**Comment by FelixKrueger** [comment]
Which version of Trim Galore were you using? I just tried 1 million reads of a random paired-end 2x125 bp data set (SRR6129181) and ran the following command:

` trim_galore --paired --length 70 R1.fastq.gz R2.fastq.gz`

All of the resulting trimmed reads come back with a read length between 70-125bp, according to FastQC.
