### ISSUE TITLE
Citing TrimGalore

### ISSUE THREAD

**Issue by minor7b5** [FelixKrueger/TrimGalore#25]
I have used TrimGalore on a recent dataset to fantastic results - thank yiu very much for creating such an effective and efficient tool!

Can you please advise how to cite the software?

**Comment by FelixKrueger** [comment]
I am glad you found it useful. We tend to recommend you simply cite the project URL (i.e. [this GitHub page](https://github.com/FelixKrueger/TrimGalore) or the URL over at the [Babraham Bioinformatics pages](http://www.bioinformatics.babraham.ac.uk/projects/trim_galore/), and/or the Cutadapt publication. Thanks, Felix

**Comment by bri2020** [comment]
Hi Felix, do you plan to use a DOI for your repository like mentioned here [](https://github.blog/2014-05-14-improving-github-for-science/)  And if not, is which year would you add for the citation? Krueger F, Trimgalore (2021), GitHub repository, https://github.com/FelixKrueger/TrimGalore. What about other developers as authors? Thanks a lot! Best wishes, Britta

**Comment by FelixKrueger** [comment]
Hi Britta,

Thanks for the tip with the DOI, turns out I had done that once before for SNPsplit already :). I have added a DOI to the README on the start page of Trim Galore.

Cheers, Felx

**Comment by bri2020** [comment]
Cool! :D Thanks a lot!
