### ISSUE TITLE
Allow max_n to equal zero

### ISSUE THREAD

**Issue by dshivak** [FelixKrueger/TrimGalore#27]
For some downstream tools that don't tolerate any Ns in the sequence, can we exclude all N-containing sequences via `--max_n 0`? Currently this complains that max_n must be between 1 and 100.

**Comment by FelixKrueger** [comment]
I have tried to change this here: 5f73283e2a1e45ee95e34dfe66df6770c9cf867a. Hope it works!

**Comment by FelixKrueger** [comment]
I have tried to change this here: 5f73283e2a1e45ee95e34dfe66df6770c9cf867a. Hope it works!
