### ISSUE TITLE
Release v0.4.5 report itself as v0.4.4_dev

### ISSUE THREAD

**Issue by greatfireball** [FelixKrueger/TrimGalore#28]
Thanks for your software `TrimGalore`! It is very helpful.

Nevertheless, it seems that I found a little issue. Release `v0.4.5` reports itself as `v0.4.4_dev`. Maybe that can be solved in the next release.

**Comment by FelixKrueger** [comment]
Sorry for the oversight, I'll make sure this will be fixed for the next release (unfortunately I can't issue a re-release but having a new release just for the version text seems a little excessive...). Cheers, Felix
