### ISSUE TITLE
Change the --rrbs option for paired-end reads

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/TrimGalore#3]
So far, the option `--rrbs` removes two additional base pairs from the 3' end of reads if adapter contamination was found, and this applies to both Read 1 and Read 2. 

Read 2 however does not technically need this since the end of Read 2 is not affected by the artificial  methylation states introduced by the [end-repair] fill-in reaction. Instead, the first couple of positions of Read 2 suffer from the same fill-in problems as standard paired-end libraries (https://sequencing.qcfail.com/articles/library-end-repair-reaction-introduces-methylation-biases-in-paired-end-pe-bisulfite-seq-applications/). Can we please change the `--rrbs` behaviour from removing 2 additional bp at the 3' end to clipping 2 bp from the 5' end of Read 2 only?

**Comment by fangquan** [comment]
Hi Felix, thank you very much.

**Comment by hxlei** [comment]
Hi,I have read the link but I'm still confused that why the end of Read 2 is not affected by the artificial methylation states introduced by the [end-repair] fill-in reaction. According to the link,  the mix of nucleotides fill in fragments with a 5′ overhang. So I think the end of Read 2 should be affected too. Could you please explain more clearly ?
Thank you very much !
