### ISSUE TITLE
Accept degenerate sequences

### ISSUE THREAD

**Issue by tiagobrc** [FelixKrueger/TrimGalore#33]
Can Trim_galore accept sequences with non-ATCGN letters? like:

CCGTCAATTYHTTTRAGT

**Comment by FelixKrueger** [comment]
I am back from the holidays, and just confirmed that the trimming of [IUPAC bases](https://cutadapt.readthedocs.io/en/stable/guide.html#wildcards) should work just fine.

So you should be able to just comment out this line with a `#` symbol at the start:
https://github.com/FelixKrueger/TrimGalore/blob/eaa59184d027c25d3474cca97483fa0b85e28c99/trim_galore#L2144 and it should then just work. Hope this helps.

**Comment by tiagobrc** [comment]
> I am back from the holidays, and just confirmed that the trimming of [IUPAC bases](https://cutadapt.readthedocs.io/en/stable/guide.html#wildcards) should work just fine.
> 
> So you should be able to just comment out this line with a `#` symbol at the start:
> [TrimGalore/trim_galore](https://github.com/FelixKrueger/TrimGalore/blob/eaa59184d027c25d3474cca97483fa0b85e28c99/trim_galore#L2144)
> 
> Line 2144 in [eaa5918](/FelixKrueger/TrimGalore/commit/eaa59184d027c25d3474cca97483fa0b85e28c99)
> 
>  die "Adapter sequence must contain DNA characters only (A,C,T,G or N)!\n"; 
> and it should then just work. Hope this helps.

THANKS!!!!
