### ISSUE TITLE
Add the cutadapt --cores option to trim_galore

### ISSUE THREAD

**Issue by sonderkar** [FelixKrueger/TrimGalore#34]
Hi, would it be possible to add the -j  (--cores) option from cutadapt to trim_galore?

**Comment by FelixKrueger** [comment]
This has been asked a few times before (e.g. [here](https://github.com/FelixKrueger/TrimGalore/issues/16) or [here](https://github.com/FelixKrueger/TrimGalore/issues/12)). In short I'm afraid for the moment it is not our highest priority at this time.
