### ISSUE TITLE
error with sequence description matching

### ISSUE THREAD

**Issue by bobkallal** [FelixKrueger/TrimGalore#35]
Hi,

I'm having an issue using TrimGalore with sequences from the SRA. When I use the following to get sequences:

fastq-dump --defline-seq '@$sn[_$rn]/$ri' --split-files file.sra

And call TrimGalore as follows:

trim_galore --paired --quality 30 --phred33 --fastqc --length 25 --retain_unpaired SRR6997627_1.fastq SRR6997627_2.fastq

I get the following error:

Trimming 1 adapter with at most 10.0% errors in single-end mode ...
cutadapt: error: At line 3: Sequence descriptions in the FASTQ file don't match ('ILLUMINA-D00365:654:HGTNWBCXX:1:1101:1284:2172_forward/1' != 'SRR6997627.1 ILLUMINA-D00365:654:HGTNWBCXX:1:1101:1284:2172 length=150').
The second sequence description must be either empty or equal to the first description.

This is what the resulting fastq files look like, for reference:

@ILLUMINA-D00365:654:HGTNWBCXX:1:1101:1284:2172_forward/1
TTTTTTGGTTTGAAAAAGAAAACATGCTTTAAATATTTCAATGTTATTTATTCACCTTATATTGATTTCGAAAAACATAATTAAAAAAGTGGTGTACCAAATCAATTACTTTCAATTGGATTAGAAAACTTTTAATTAAATAGAATTTTT
+SRR6997627.1 ILLUMINA-D00365:654:HGTNWBCXX:1:1101:1284:2172 length=150
DDDDDHHIIIIIGIIIIIHIIHGIIIIIIIIHIIIIIIHIIIIIIHIIIGFHIHIIIIIIHIIIIHIIIIIIHIIIIIIHIHHHIHIGHGFEGHIIHIIGHGHIHIIIIIIIIHGEHHHIHGIIHHIIHEHIIHIIIIIHIHHHHIIIII

Do you have any recommendation for dealing with this error? Thank you!

**Comment by FelixKrueger** [comment]
Hi @bobkallal,

Cutadapt is enforcing the [FastQ format specifications](https://en.wikipedia.org/wiki/FASTQ_format), so the third line has to be either *exactly the same* as the first line (only that line 1 has to start with an `@` symbol and line 3 has to start with a `+` symbol, or line 3 may be empty (i.e. just a `+` symbol on its own.
So:
```
@ILLUMINA-D00365:654:HGTNWBCXX:1:1101:1284:2172_forward/1
TTTTTTGGTTTGAAAAAGAAAACATGCTTTAAATATTTCAATGTTATTTATTCACCTTATATTGATTTCGAAAAACATAATTAAAAAAGTGGTGTACCAAATCAATTACTTTCAATTGGATTAGAAAACTTTTAATTAAATAGAATTTTT
+
DDDDDHHIIIIIGIIIIIHIIHGIIIIIIIIHIIIIIIHIIIIIIHIIIGFHIHIIIIIIHIIIIHIIIIIIHIIIIIIHIHHHIHIGHGFEGHIIHIIGHGHIHIIIIIIIIHGEHHHIHGIIHHIIHEHIIHIIIIIHIHHHHIIIII
```
or 
```
@ILLUMINA-D00365:654:HGTNWBCXX:1:1101:1284:2172_forward/1
TTTTTTGGTTTGAAAAAGAAAACATGCTTTAAATATTTCAATGTTATTTATTCACCTTATATTGATTTCGAAAAACATAATTAAAAAAGTGGTGTACCAAATCAATTACTTTCAATTGGATTAGAAAACTTTTAATTAAATAGAATTTTT
+ILLUMINA-D00365:654:HGTNWBCXX:1:1101:1284:2172_forward/1
DDDDDHHIIIIIGIIIIIHIIHGIIIIIIIIHIIIIIIHIIIIIIHIIIGFHIHIIIIIIHIIIIHIIIIIIHIIIIIIHIHHHIHIGHGFEGHIIHIIGHGHIHIIIIIIIIHGEHHHIHGIIHHIIHEHIIHIIIIIHIHHHHIIIII
```
would be acceptable. It seems that your `fastq-dump` command is producing this weird sequence, maybe you drop `--defline-seq '@$sn[_$rn]/$ri'` and try it again? Alternatively, you could write a quick script or use a clever `sed/awk` command to replace line 3 with a `+` and write it out again. 
Hope this helps. Felix

**Comment by FelixKrueger** [comment]
Glad to hear! Cheers, Felix
