### ISSUE TITLE
Stop trimgalore from searching for adaptor

### ISSUE THREAD

**Issue by djbradshaw2** [FelixKrueger/TrimGalore#37]
Dear Whom It May Concern,

I am just trying to use trim_galore to remove primers from my paired end 16S sequences (first 19 bases of R1 and first 20 bases of R2) and trim by quality control. I do not want the program to search for an adapter because it has been removed prior to being sent to me, but by default it does search for the Illumina one and will randomly cut in the middle of some of my sequences even with an error rate of 0% which makes them obsolete. Is there any way to deal with this? To turn off the adapter search? Thank you for your time and help. 

Sincerely, 

David Bradshaw

**Comment by FelixKrueger** [comment]
Hi David,
It doesn't currently have a specific mode where it doesn't look for adapter at all, but you could simply look for an adapter such as `X` which is not present, and thus not removed from your data. The command would simply be:

`trim_galore -a X file.fastq.gz`

Hope this helps. 
Best, Felix

**Comment by djbradshaw2** [comment]
Dear Felix,
Thank you very much, that worked. 
Sincerely, 
David

**Comment by huangwb8** [comment]
@djbradshaw2 @FelixKrueger Hi~This is very helpful!
But I'm still new to use trim_galore to remove primers. How could I do that? Thanks!

**Comment by FelixKrueger** [comment]
Hi @huangwb8 

If you want to remove a specific primer sequence you could use `-a PRIMERSEQUENCE`. Just as a side note, we find it is often not necessary to remove every little bit of contamination, e.g. primer sequences typically do't align to a genome anyway. But this depends of course somewhat on your application.

**Comment by huangwb8** [comment]
@FelixKrueger Thanks~Actually, I also found even in the small RNA-Seq data, alignment would not be affected the regardless of a bit primer contamination. Just as you have said, it would not align to reference. Your suggestion is very pertinent!
