### ISSUE TITLE
Problem running paired mode with 2 input files

### ISSUE THREAD

**Issue by Rhinogradentia** [FelixKrueger/TrimGalore#38]
Hi,

I tried to run trim_galore in paired mode with two input files (B1_1.fq, B1_2.fq) and got following error:

> Please provide an even number of input files for paired-end FastQ trimming! Abort ...

My command was this:
`trim_galore --paired −−fastqc B1_1.fq B1_2.fq`

What am I doing wrong?

Any help really appreciated - thank you in advance.

best regards,
Nadine

**Comment by Rhinogradentia** [comment]
Thank you Felix,
although I was sure I didn't forget it, I tried it again an now it seems to work - with another Java Runtime related error. I will have a look into this by myself first.

best regards
Nadine

**Comment by matthewholding28** [comment]
I just came across the issue with the current github version. To fix it, I just moved the --paired flag to a place immediately before the listing of the paired input files. In other words, all other flags must come first, and the last part of the command must be --paired *R1.fq.gz *R2.fq.gz
