### ISSUE TITLE
adapter regular expression

### ISSUE THREAD

**Issue by wangjiawen2013** [FelixKrueger/TrimGalore#40]
Dear, 
There are two adapters in my fastq (CATG/ TGCA) , can I remove them with regular expression CATG|TGCA ?

**Comment by FelixKrueger** [comment]
I am afraid this is not possible within Trim Galore, but you would have to run two consecutive runs.

**Comment by wangjiawen2013** [comment]
> I am afraid this is not possible within Trim Galore, but you would have to run two consecutive runs.

the adapter sequence is CATG, but I find the sequence that don't have CATG are also cut. I don't know why. Are the adapter too short ?

**Comment by wangjiawen2013** [comment]
Good advice, thanks!
