### ISSUE TITLE
Problem with cutadapt line1

### ISSUE THREAD

**Issue by ChristophKramer** [FelixKrueger/TrimGalore#44]
Hello,
I want to use TrimGalore owith a fastq file. This is the command I am using:

TrimGalore-0.5.0/trim_galore -q 25 --fastqc --small_rna --max_length 28 --length 17 --max_n 5 -o GSM1585389_Trim_QC/ GSM1585389.fastq

I get the following erroer message:
"This is cutadapt 1.16 with Python 2.7.13
Command line parameters: -f fastq -e 0.1 -q 25 -O 1 -a TGGAATTCTCGG GSM1585389.fastq
Running on 1 core
Trimming 1 adapter with at most 10.0% errors in single-end mode ...
cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but found '\n'

Cutadapt terminated with exit signal: '256'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong..."

If I run cutadapt with the command :
cutadapt -f fastq -e 0.1 -q 25 -O 1 -a TGGAATTCTCGG GSM1585389.fastq

it works just fine. Any Idea what I can do about this issue?

Greetings
Christoph Kramer

**Comment by ChristophKramer** [comment]
Apparantly the last line of my fastq file was empty and cutadapt couldn't cope with that.
I removed it manually and now it works just fine.

Pardon me for the inconvinience.

**Comment by FelixKrueger** [comment]
I'm glad this one sorted itself out.
