### ISSUE TITLE
Failed to write to file issue - create output folder if it doesn't exist already

### ISSUE THREAD

**Issue by itiago** [FelixKrueger/TrimGalore#45]
Hi, I tried to run trimgalore but I have this error every time...
Can someone help me 
Kind regrards

(base) deepbio@deepbio-virtual-machine:~/Documents/Genomes/Genomas_GATC/Cyanobacterias/LN$ ~/TrimGalore-0.4.5/trim_galore -o LN_READ_QC --dont_gzip --paired --retain_unpaired --trim1 LN_RAW_READS/NG-14245_LN_lib279042_6140_5_1.fastq LN_RAW_READS/NG-14245_LN_lib279042_6140_5_2.fastq
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Path to Cutadapt set as: 'cutadapt' (default)
1.16
Cutadapt seems to be working fine (tested command 'cutadapt --version')

AUTO-DETECTING ADAPTER TYPE
===========================
Attempting to auto-detect adapter type from the first 1 million sequences of the first file (>> LN_RAW_READS/NG-14245_LN_lib279042_6140_5_1.fastq <<)

Found perfect matches for the following adapter sequences:
Adapter type    Count   Sequence        Sequences analysed      Percentage
Illumina        7699    AGATCGGAAGAGC   1000000 0.77
smallRNA        3       TGGAATTCTCGG    1000000 0.00
Nextera 0       CTGTCTCTTATA    1000000 0.00
Using Illumina adapter for trimming (count: 7699). Second best hit was smallRNA (count: 3)

Failed to write to file 'NG-14245_LN_lib279042_6140_5_1.fastq_trimming_report.txt': No such file or directory

**Comment by FelixKrueger** [comment]
Hi @itiago,

I think the only problem with your command is that you you specify an output folder that does not exist. If you selected e.g. `-o LN_RAW_READS`, I am sure it would work fine. 

Just a quick remark regarding the option `--trim1`: This was necessary for Bowtie 1 alignments, but
if you are planning to use Bowtie2, BWA etc. you don't need to specify this option.

I can add to the list that Trim Galore creates output files if they do not exist already.

**Comment by itiago** [comment]
Felix
You are correct.
Thank you.
I did not understand the meaning of this sentence:
"I can add to the list that Trim Galore creates output files if they do not
exist already."

Best
Igor

Na(o) sábado, 23/02/2019, 13:49, FelixKrueger <notifications@github.com>
escreveu:

**Comment by FelixKrueger** [comment]
Hi Igor, 

sorry for being so cryptic. I meant I will add it to my list of things I need to do when I am back at work. And I have just added the functionality to create the output directory for you in case a folder was specified that did not exist already. So if you were to clone the latest development version your initial command should now also work. Addressed here: b60b0bebae4a6202c9d6dcc6151c07d1715784c2.

All the best, Felix
