### ISSUE TITLE
--max_n does not seem to work in RRBS mode

### ISSUE THREAD

**Issue by pinetree1** [FelixKrueger/TrimGalore#46]
Tried --max_n 0 to exclude reads with N, but there are still reads with Ns in the trimmed fastq. Tried --max_n 1 as well, but N reads with more than 1 N are not removed. In both cases, the report said: 
Sequences removed because they contained more Ns than the cutoff of 1:	0 (0.0%)

**Comment by pinetree1** [comment]
I am running it on single-end fastq file, with options: --rrbs --max_n 1. Looks like it works when --max_n 1 is used without -rrbs.

**Comment by FelixKrueger** [comment]
It is a possibility that it doesn't work in `--rrbs` mode, I'll take a look at this tomorrow.

**Comment by FelixKrueger** [comment]
I just found the following text in `trim_galore --help`:

```
--trim-n                Removes Ns from either side of the read. This option does currently not work in RRBS mode.
```

That might explain what you are seeing :)

**Comment by FelixKrueger** [comment]
The option `--max_n INT` should now also work for single-end RRBS files. Added here: 336061434910cce82e80426a2f28c36d81c4dae3.

**Comment by pinetree1** [comment]
Yes, it works now. Thanks!
