### ISSUE TITLE
cutadapt: error: no such option: -j

### ISSUE THREAD

**Issue by krostifangers** [FelixKrueger/TrimGalore#48]
Hello
I ran trim_galore using the following command line:
./trim_galore --gzip --illumina SRR1508529.fastq

I then get the following:
Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Writing report to 'SRR1508528.fastq_trimming_report.txt'

SUMMARISING RUN PARAMETERS
==========================
Input filename: SRR1508528.fastq
Trimming mode: single-end
Trim Galore version: 0.6.0
Cutadapt version: 1.12
Number of cores used for trimming: 1
Quality Phred score cutoff: 30
Quality encoding type selected: ASCII+33
Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; user defined)
Maximum trimming error rate: 0.1 (default)
Minimum required adapter overlap (stringency): 1 bp
Minimum required sequence length before a sequence gets removed: 20 bp
Output file(s) will be GZIP compressed

Writing final adapter and quality trimmed output to SRR1508528_trimmed.fq.gz

  >>> Now performing quality (cutoff '-q 30') and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file SRR1508528.fastq <<< 
cutadapt version 1.12
Copyright (C) 2010-2016 Marcel Martin <marcel.martin@scilifelab.se>

cutadapt removes adapter sequences from high-throughput sequencing reads.

Usage:
    cutadapt -a ADAPTER [options] [-o output.fastq] input.fastq

For paired-end reads:
    cutadapt -a ADAPT1 -A ADAPT2 [options] -o out1.fastq -p out2.fastq in1.fastq in2.fastq

Replace "ADAPTER" with the actual sequence of your 3' adapter. IUPAC wildcard
characters are supported. The reverse complement is *not* automatically
searched. All reads from input.fastq will be written to output.fastq with the
adapter sequence removed. Adapter matching is error-tolerant. Multiple adapter
sequences can be given (use further -a options), but only the best-matching
adapter will be removed.

Input may also be in FASTA format. Compressed input and output is supported and
auto-detected from the file name (.gz, .xz, .bz2). Use the file name '-' for
standard input/output. Without the -o option, output is sent to standard output.

Citation:

Marcel Martin. Cutadapt removes adapter sequences from high-throughput
sequencing reads. EMBnet.Journal, 17(1):10-12, May 2011.
http://dx.doi.org/10.14806/ej.17.1.200

Use "cutadapt --help" to see all command-line options.
See http://cutadapt.readthedocs.org/ for full documentation.

cutadapt: error: no such option: -j

Cutadapt terminated with exit signal: '512'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

So I do not understand why option -j is invoked as I did not set it in the command line
Please let me know if you find an explanation
All the best
christophe

**Comment by FelixKrueger** [comment]
Ah right, it turns out that your installation of Cutadapt is too old. You require at least version 1.15 in order to use the option `-j`. So the fix for you is to simply upgrade Cutadapt, and then it should all work.

I should probably add a check to see if the Cutadapt version used is older than 1.15, and disable -j in Trim Galore then. This will have to wait at least until tomorrow as I am tied up today.

Best, Felix

**Comment by FelixKrueger** [comment]
Hi Christophe,

I have now added a new check so that very old versions of Cutadapt are handled differently. Would you mind cloning the latest development version and see if that works with your old version of Cutadapt?
Thanks, Felix

Addressed here 4d15e350156d65d437d2d90846d067892e5688c5

**Comment by krostifangers** [comment]
Thank you so much Felix 
Unfortunately I already upgraded my cutadapt version. But thank you for your help, it worked fine. 
Have a good day 
all the best 
christophe 



De: "FelixKrueger" <notifications@github.com> 
À: "FelixKrueger/TrimGalore" <TrimGalore@noreply.github.com> 
Cc: "Christophe LEMAIRE" <christophe.lemaire@univ-angers.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 8 Mars 2019 11:55:48 
Objet: Re: [FelixKrueger/TrimGalore] cutadapt: error: no such option: -j (#48) 



Hi Christophe, 

I have now added a new check so that very old versions of Cutadapt are handled differently. Would you mind cloning the latest development version and see if that works with your old version of Cutadapt? 
Thanks, Felix 

Addressed here [ https://github.com/FelixKrueger/TrimGalore/commit/4d15e350156d65d437d2d90846d067892e5688c5 | 4d15e35 ]

**Comment by avitalsteiman** [comment]
Hi,
I just ran trim_galore after downloading and installing it today and received the same error. I'm using cutadapt version 1.9.1 so maybe your check doesn't work? I'm going to update the cutadapt, but I'll attach the report for you in case you want to change something.
Thanks!

[SRR7119141_1.fastq_trimming_report.txt](https://github.com/FelixKrueger/TrimGalore/files/3054563/SRR7119141_1.fastq_trimming_report.txt)

**Comment by FelixKrueger** [comment]
Have you tried cloning the current development version, and tried again?

**Comment by avitalsteiman** [comment]
Hi,
I now see that I downloaded the version (0.6.0) (I copied the line from the
installation example) so maybe it was not the most updated version.
Avital

**Comment by rotifergirl** [comment]
Hi, 
I have the same problem. 
I have cutadapt v 1.2.1.

I tried using TrimGalore v0.6.0, and got this error. I got the same error when I cloned the current github version too.

Any other suggestions?

Thanks
Julie

**Comment by FelixKrueger** [comment]
Hi Julie,

Could you please post of mail me the exact text you see on screen, maybe this reveals something I could use to tackle the issue. Cheers, Felix

**Comment by rotifergirl** [comment]
Hi Felix,

Sorry for the slow response, here is the text I get when trying to run trimgalore-0.6.0

`~/TrimGalore-0.6.0/trim_galore IK1_all_R1.fq IK1_all_R2.fq -o trimgalore_test`

> Multicore support not enabled. Proceeding with single-core trimming.
> Path to Cutadapt set as: 'cutadapt' (default)
> Cutadapt seems to be working fine (tested command 'cutadapt --version')
> No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)
> 
> Output directory trimgalore_test/ doesn't exist, creating it for you...
> 
> Output will be written into the directory: /automounts/workspace/workspace/markwelchlab/HIMBplic/PacBio/IK1/trimgalore_test/
> 
> 
> AUTO-DETECTING ADAPTER TYPE
> ===========================
> Attempting to auto-detect adapter type from the first 1 million sequences of the first file (>> IK1_all_R1.fq <<)
> 
> Found perfect matches for the following adapter sequences:
> Adapter type	Count	Sequence	Sequences analysed	Percentage
> Illumina	3928	AGATCGGAAGAGC	1000000	0.39
> Nextera	1	CTGTCTCTTATA	1000000	0.00
> smallRNA	0	TGGAATTCTCGG	1000000	0.00
> Using Illumina adapter for trimming (count: 3928). Second best hit was Nextera (count: 1)
> 
> Writing report to '/automounts/workspace/workspace/markwelchlab/HIMBplic/PacBio/IK1/trimgalore_test/IK1_all_R1.fq_trimming_report.txt'
> 
> SUMMARISING RUN PARAMETERS
> ==========================
> Input filename: IK1_all_R1.fq
> Trimming mode: single-end
> Trim Galore version: 0.6.0
> Cutadapt version: 1.2.1
> Number of cores used for trimming: 1
> Quality Phred score cutoff: 20
> Quality encoding type selected: ASCII+33
> Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; auto-detected)
> Maximum trimming error rate: 0.1 (default)
> Minimum required adapter overlap (stringency): 1 bp
> Minimum required sequence length before a sequence gets removed: 20 bp
> 
> Writing final adapter and quality trimmed output to IK1_all_R1_trimmed.fq
> 
> 
>   >>> Now performing quality (cutoff '-q 20') and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file IK1_all_R1.fq <<< 
> Usage: cutadapt [options] <FASTA/FASTQ FILE> [<QUALITY FILE>]
> 
> Reads a FASTA or FASTQ file, finds and removes adapters,
> and writes the changed sequence to standard output.
> When finished, statistics are printed to standard error.
> 
> Use a dash "-" as file name to read from standard input
> (FASTA/FASTQ is autodetected).
> 
> If two file names are given, the first must be a .fasta or .csfasta
> file and the second must be a .qual file. This is the file format
> used by some 454 software and by the SOLiD sequencer.
> If you have color space data, you still need to provide the -c option
> to correctly deal with color space!
> 
> If the name of any input or output file ends with '.gz', it is
> assumed to be gzip-compressed.
> 
> If you want to search for the reverse complement of an adapter, you must
> provide an additional adapter sequence using another -a, -b or -g parameter.
> 
> If the input sequences are in color space, the adapter
> can be given in either color space (as a string of digits 0, 1, 2, 3) or in
> nucleotide space.
> 
> EXAMPLE
> 
> Assuming your sequencing data is available as a FASTQ file, use this
> command line:
> $ cutadapt -e ERROR-RATE -a ADAPTER-SEQUENCE input.fastq > output.fastq
> 
> See the README file for more help and examples.
> 
> Options:
>   --version             show program's version number and exit
>   -h, --help            show this help message and exit
>   -f FORMAT, --format=FORMAT
>                         Input file format; can be either 'fasta', 'fastq' or
>                         'sra-fastq'. Ignored when reading csfasta/qual files
>                         (default: auto-detect from file name extension).
> 
>   Options that influence how the adapters are found:
>     Each of the following three parameters (-a, -b, -g) can be used
>     multiple times and in any combination to search for an entire set of
>     adapters of possibly different types. All of the given adapters will
>     be searched for in each read, but only the best matching one will be
>     trimmed (but see the --times option).
> 
>     -a ADAPTER, --adapter=ADAPTER
>                         Sequence of an adapter that was ligated to the 3' end.
>                         The adapter itself and anything that follows is
>                         trimmed.
>     -b ADAPTER, --anywhere=ADAPTER
>                         Sequence of an adapter that was ligated to the 5' or
>                         3' end. If the adapter is found within the read or
>                         overlapping the 3' end of the read, the behavior is
>                         the same as for the -a option. If the adapter overlaps
>                         the 5' end (beginning of the read), the initial
>                         portion of the read matching the adapter is trimmed,
>                         but anything that follows is kept.
>     -g ADAPTER, --front=ADAPTER
>                         Sequence of an adapter that was ligated to the 5' end.
>                         If the adapter sequence starts with the character '^',
>                         the adapter is 'anchored'. An anchored adapter must
>                         appear in its entirety at the 5' end of the read (it
>                         is a prefix of the read). A non-anchored adapter may
>                         appear partially at the 5' end, or it may occur within
>                         the read. If it is found within a read, the sequence
>                         preceding the adapter is also trimmed. In all cases,
>                         the adapter itself is trimmed.
>     -e ERROR_RATE, --error-rate=ERROR_RATE
>                         Maximum allowed error rate (no. of errors divided by
>                         the length of the matching region) (default: 0.1)
>     -n COUNT, --times=COUNT
>                         Try to remove adapters at most COUNT times. Useful
>                         when an adapter gets appended multiple times (default:
>                         1).
>     -O LENGTH, --overlap=LENGTH
>                         Minimum overlap length. If the overlap between the
>                         read and the adapter is shorter than LENGTH, the read
>                         is not modified.This reduces the no. of bases trimmed
>                         purely due to short random adapter matches (default:
>                         3).
>     --match-read-wildcards
>                         Allow 'N's in the read as matches to the adapter
>                         (default: False).
>     -N, --no-match-adapter-wildcards
>                         Do not treat 'N' in the adapter sequence as wildcards.
>                         This is needed when you want to search for literal 'N'
>                         characters.
> 
>   Options for filtering of processed reads:
>     --discard-trimmed, --discard
>                         Discard reads that contain the adapter instead of
>                         trimming them. Also use -O in order to avoid throwing
>                         away too many randomly matching reads!
>     --discard-untrimmed, --trimmed-only
>                         Discard reads that do not contain the adapter.
>     -m LENGTH, --minimum-length=LENGTH
>                         Discard trimmed reads that are shorter than LENGTH.
>                         Reads that are too short even before adapter removal
>                         are also discarded. In colorspace, an initial primer
>                         is not counted (default: 0).
>     -M LENGTH, --maximum-length=LENGTH
>                         Discard trimmed reads that are longer than LENGTH.
>                         Reads that are too long even before adapter removal
>                         are also discarded. In colorspace, an initial primer
>                         is not counted (default: no limit).
> 
>   Options that influence what gets output to where:
>     -o FILE, --output=FILE
>                         Write the modified sequences to this file instead of
>                         standard output and send the summary report to
>                         standard output. The format is FASTQ if qualities are
>                         available, FASTA otherwise. (default: standard output)
>     --info-file=FILE    Write information about each read and its adapter
>                         matches into FILE. Currently experimental: Expect the
>                         file format to change!
>     -r FILE, --rest-file=FILE
>                         When the adapter matches in the middle of a read,
>                         write the rest (after the adapter) into a file. Use -
>                         for standard output.
>     --wildcard-file=FILE
>                         When the adapter has wildcard bases ('N's) write
>                         adapter bases matching wildcard positions to FILE. Use
>                         - for standard output. When there are indels in the
>                         alignment, this may occasionally not be quite
>                         accurate.
>     --too-short-output=FILE
>                         Write reads that are too short (according to length
>                         specified by -m) to FILE. (default: discard reads)
>     --untrimmed-output=FILE
>                         Write reads that do not contain the adapter to FILE,
>                         instead of writing them to the regular output file.
>                         (default: output to same file as trimmed)
> 
>   Additional modifications to the reads:
>     -q CUTOFF, --quality-cutoff=CUTOFF
>                         Trim low-quality ends from reads before adapter
>                         removal. The algorithm is the same as the one used by
>                         BWA (Subtract CUTOFF from all qualities; compute
>                         partial sums from all indices to the end of the
>                         sequence; cut sequence at the index at which the sum
>                         is minimal) (default: 0)
>     --quality-base=QUALITY_BASE
>                         Assume that quality values are encoded as
>                         ascii(quality + QUALITY_BASE). The default (33) is
>                         usually correct, except for reads produced by some
>                         versions of the Illumina pipeline, where this should
>                         be set to 64. (default: 33)
>     -x PREFIX, --prefix=PREFIX
>                         Add this prefix to read names
>     -y SUFFIX, --suffix=SUFFIX
>                         Add this suffix to read names
>     --strip-suffix=STRIP_SUFFIX
>                         Remove this suffix from read names if present. Can be
>                         given multiple times.
>     -c, --colorspace    Colorspace mode: Also trim the color that is adjacent
>                         to the found adapter.
>     -d, --double-encode
>                         When in color space, double-encode colors (map
>                         0,1,2,3,4 to A,C,G,T,N).
>     -t, --trim-primer   When in color space, trim primer base and the first
>                         color (which is the transition to the first
>                         nucleotide)
>     --strip-f3          For color space: Strip the _F3 suffix of read names
>     --maq, --bwa        MAQ- and BWA-compatible color space output. This
>                         enables -c, -d, -t, --strip-f3, -y '/1' and -z.
>     --length-tag=TAG    Search for TAG followed by a decimal number in the
>                         name of the read (description/comment field of the
>                         FASTA or FASTQ file). Replace the decimal number with
>                         the correct length of the trimmed read. For example,
>                         use --length-tag 'length=' to correct fields like
>                         'length=123'.
>     -z, --zero-cap      Change negative quality values to zero (workaround to
>                         avoid segmentation faults in BWA)
> 
> cutadapt: error: no such option: -j
> 
> 
> Cutadapt terminated with exit signal: '512'.
> Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

**Comment by FelixKrueger** [comment]
Can you please clone the latest development version (0.6.1_dev), and try again? This error should no longer occur. Cheers, Felix

**Comment by rotifergirl** [comment]
I get the same exact message and error, sorry

**Comment by FelixKrueger** [comment]
Does it now say version 0.6.1_dev?

**Comment by rotifergirl** [comment]
Yes

**Comment by FelixKrueger** [comment]
Hmm, can you try specifying `--paired` as well and link the on screen text? I will try to take another look tomorrow. thanks, Felix

**Comment by rotifergirl** [comment]
Unfortunately that lead to the same problem

**Comment by FelixKrueger** [comment]
Can you please download the attached version, and run it again on your system I have tried to add some more statements that should identify where it is going wrong. Can you please post the on-screen output here, or email me the log if it goes wrong again.
[trim_galore.zip](https://github.com/FelixKrueger/TrimGalore/files/3094141/trim_galore.zip)

I suspect that the problem lies with the fact that the version number reported (1.2.1) is not a number, and therefore fails the test we were using. Thanks, Felix

**Comment by rotifergirl** [comment]
I've tried that and get the same error. I also tried then by specifying --cores 4, and then I get a different error 

`~/TrimGalore_gitdev/trim_galore --paired --cores 4 IK1_all_R1.fq IK1_all_R2.fq -o trimgalore_test`
> Path to Cutadapt set as: 'cutadapt' (default)
> Cutadapt seems to be working fine (tested command 'cutadapt --version')
> Use of uninitialized value $_ in pattern match (m//) at /users/jblommaert/TrimGalore_gitdev/trim_galore line 2186.
> Use of uninitialized value $python_return in scalar chomp at /users/jblommaert/TrimGalore_gitdev/trim_galore line 2193.
> Use of uninitialized value $python_return in pattern match (m//) at /users/jblommaert/TrimGalore_gitdev/trim_galore line 2196.
> Use of uninitialized value $python_return in pattern match (m//) at /users/jblommaert/TrimGalore_gitdev/trim_galore line 2199.
> No Python detected. Python required to run Cutadapt!
> 

I've also just run cutadapt successfully on its own (and double checked that python is there, v2.7.15)

**Comment by FelixKrueger** [comment]
OK I have now set up an installation of the (**nearly 7 year out of date!!**) version 1.2.1 of Cutadapt, and saw as well that the versioning check was failing. What Trim Galore does now is to:
1) remove any sub-subversion from the version number, so `1.2.1` becomes `1.2`
2) split the version into a major version (here `1`) and a sub-version (here `2`)
3) compare sequentially whether the major version was 1 (quite old), and if yes, whether the sub-version was smaller than 15 (very old). If the latter is found, the option `-j ` is simply removed from the command. 

I could get this to work fine on my test environment, could you please give it a whirl on your end?

[trim_galore.zip](https://github.com/FelixKrueger/TrimGalore/files/3095893/trim_galore.zip)

Apart from the fact that Trim Galore should be able to cope with old versions, I really think you should upgrade your Cutadapt installation, there have been lots of new releases and improvements in the last six and a half years...)
