### ISSUE TITLE
Disabling adapter removal process while running

### ISSUE THREAD

**Issue by EgeDede562** [FelixKrueger/TrimGalore#51]
Dear Felix,

I am trying to do a quality trimming with trimgalore with fastq files that have already had their adaptor sequences removed and unfortunately I do not have access to the original files. When I run trimgalore however it autodetects the illumina adaptor and tries to remove it. Is there any way of disabling this step? or should I just increase my specificity parameter to 13-14? (as it was 1, I clipped a lot of reads by accident).

Thank you

**Comment by FelixKrueger** [comment]
You could just select an adapter sequence that doesn't exist, e.g. `-a X`. That way, no adapter sequence should be clipped. Cheers, Felix
