### ISSUE TITLE
Issue with basename

### ISSUE THREAD

**Issue by jovesus** [FelixKrueger/TrimGalore#54]
Hi,

The output files of Bismark on paired-end sequences with ```--basename``` parameter are supposed to be:

```
renamed_bismark_bt2_pe.bam
```

But now the extra tag, ```_val_1``` is kept:
```
renamed_val_1_bismark_bt2_pe.bam
```

I think it needs a fix as well. Thank you.

**Comment by FelixKrueger** [comment]
Not quite sure I understand that question. A command like this:
`bismark --basename renamed -1 test1_val_1.fq  -2 test2_val_2.fq --genome /bi/scratch/Genomes/Human/GRCh38` 

produces an output file named `renamed_pe.bam`.

Dropping the `--basename`:

`bismark -1 test1_val_1.fq  -2 test2_val_2.fq --genome /bi/scratch/Genomes/Human/GRCh38` 

yields `test1_val_1_bismark_bt2_pe.bam`

**Comment by FelixKrueger** [comment]
any update on this?

**Comment by jovesus** [comment]
Sorry for the late reply. It is all fine now. Thank you.

**Comment by FelixKrueger** [comment]
Excellent, thank for the reply.
