### ISSUE TITLE
Using trim_galore without adapters

### ISSUE THREAD

**Issue by raivivek** [FelixKrueger/TrimGalore#55]
Hi,

I was wondering if it's possible to use cutadapt/trim_galore without specifying any adapters -- something like https://github.com/harvardinformatics/NGmerge or https://github.com/parkerlab/cta which is routinely used with ATAC-seq data

Thanks!

**Comment by FelixKrueger** [comment]
To not perform any adapter trimming (but carry out quality trimming), you could specify `-a X`. Would that help?

**Comment by raivivek** [comment]
Thanks for getting back!

That'd be different that what these methods do. They implement a adapter removal strategy that does not rely on specifying particular adapters. Basically, align two paired-end reads and trim the overhangs (which would be adapters). Does trim_galore support such trimming strategy?

**Comment by FelixKrueger** [comment]
Ah right, I got that wrong. No, I am afraid this is not something Trim Galore does. The main reason for this is that for most sequencing applications we know the adapter sequence of the contamination, so we can identify and remove if that way.
