### ISSUE TITLE
Errors with cutadapt command call

### ISSUE THREAD

**Issue by Lanilen** [FelixKrueger/TrimGalore#56]
Hi!

I have updated trim_galore to the latest version, and I seem to have run into something odd. Whenever I specify a number of cores with -j or --cores, I get the following error:

Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 2.1
Use of uninitialized value $_ in pattern match (m//) at /home/roger/bin/trim_galore line 2206.
Use of uninitialized value $python_return in scalar chomp at /home/roger/bin/trim_galore line 2213.
Use of uninitialized value $python_return in pattern match (m//) at /home/roger/bin/trim_galore line 2216.
Use of uninitialized value $python_return in pattern match (m//) at /home/roger/bin/trim_galore line 2219.
No Python detected. Python required to run Cutadapt!

The odd thing is that trim_galore was working perfectly before (I only updated because I had a version with the --basename bug). I think it's the $_ match at lines 2206 and 2208 that should actually be $shebang, but I could be wrong. I changed those two lines and the -j option parsed OK.

If I run it without specifying cores, I get a dump that seems to be a malformed system call to cutadapt.

I fixed that one by doing this replacement in all appropriate system call lines:

-$path_to_cutadapt  $cores -e $error_rate
+$path_to_cutadapt -j $cores -e $error_rate

With these changes my test data looks like it ran fine.

Anyway, I didn't want to do a pull request with these changes because I'm not sure if this would hardcode options that my particular version of cutadapt can read but others can't, or if I was supposed to do it differently.

**Comment by FelixKrueger** [comment]
Hi Roger, 

I think you are right about the first pattern match. I have just changed that, could you please clone the current development version and let me know if that works now? 

Regarding the second issue, could you provide some more details about the malformed command?

**Comment by Lanilen** [comment]
Hi Felix,

Sure no problem. Let's say I start with this command with the test data:

../trim_galore --paired -q 30 clock_10K_R1.fastq.gz clock_10K_R2.fastq.gz

The output I get is:

---

Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 2.1
single-core operation.
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)



AUTO-DETECTING ADAPTER TYPE
===========================
Attempting to auto-detect adapter type from the first 1 million sequences of the first file (>> clock_10K_R1.fastq.gz <<)

Found perfect matches for the following adapter sequences:
Adapter type	Count	Sequence	Sequences analysed	Percentage
Illumina	488	AGATCGGAAGAGC	10000	4.88
smallRNA	0	TGGAATTCTCGG	10000	0.00
Nextera	0	CTGTCTCTTATA	10000	0.00
Using Illumina adapter for trimming (count: 488). Second best hit was smallRNA (count: 0)

Writing report to 'clock_10K_R1.fastq.gz_trimming_report.txt'

SUMMARISING RUN PARAMETERS
==========================
Input filename: clock_10K_R1.fastq.gz
Trimming mode: paired-end
Trim Galore version: 0.6.1_dev
Cutadapt version: 2.1
Number of cores used for trimming: 1
Quality Phred score cutoff: 30
Quality encoding type selected: ASCII+33
Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; auto-detected)
Maximum trimming error rate: 0.1 (default)
Minimum required adapter overlap (stringency): 1 bp
Minimum required sequence length for both reads before a sequence pair gets removed: 20 bp
Output file(s) will be GZIP compressed

Cutadapt seems to be fairly up-to-date (version 2.1). Setting -j 1
Writing final adapter and quality trimmed output to clock_10K_R1_trimmed.fq.gz


  >>> Now performing quality (cutoff '-q 30') and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file clock_10K_R1.fastq.gz <<< 
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: unrecognized arguments: clock_10K_R1.fastq.gz


Cutadapt terminated with exit signal: '512'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

---

If I change the following lines:

1018 - $pid = open3 (\*WRITER, \*TRIM, \*ERROR, "$path_to_cutadapt   $cores -e $error_rate $quality_cutoff -O $stringency $trim_n -a $adapter $filename") or die "Failed to launch Cutadapt: $!";
1023 - $pid = open3 (\*WRITER, \*TRIM, \*ERROR, "$path_to_cutadapt   $cores -e $error_rate $quality_cutoff -O $stringency $trim_n -a $a2 $filename") or die "Failed to launch Cutadapt: $!";
1030 - $pid = open3 (\*WRITER, \*TRIM, \*ERROR, "$path_to_cutadapt   $cores -e $error_rate $quality_cutoff -O $stringency $trim_n -a $adapter $filename") or die "Failed to launch Cutadapt: $!";

To these:

1018 - $pid = open3 (\*WRITER, \*TRIM, \*ERROR, "$path_to_cutadapt  -j $cores -e $error_rate $quality_cutoff -O $stringency $trim_n -a $adapter $filename") or die "Failed to launch Cutadapt: $!";
1023 - $pid = open3 (\*WRITER, \*TRIM, \*ERROR, "$path_to_cutadapt  -j $cores -e $error_rate $quality_cutoff -O $stringency $trim_n -a $a2 $filename") or die "Failed to launch Cutadapt: $!";
1030 - $pid = open3 (\*WRITER, \*TRIM, \*ERROR, "$path_to_cutadapt  -j $cores -e $error_rate $quality_cutoff -O $stringency $trim_n -a $adapter $filename") or die "Failed to launch Cutadapt: $!";

Then everything runs fine. What I'm not sure is if it's missing the -j flag, or if it was supposed to be included in the $cores variable somehow and it wasn't.

**Comment by FelixKrueger** [comment]
Thanks for the text, I think I have found the issue. For the same command I got exactly the same text, but then it continued to run through just fine... 

I believe the problem was that for Cutadapt versions 2 or higher it printed to screen:

`warn "Cutadapt seems to be fairly up-to-date (version $cutadapt_version). Setting -j $cores\n";`

but it did not actually set `$cores` to `-j $cores` as promised. For me it worked because we are still using v1.18, for which it works fine. 

I have now changed the behaviour, would you mind testing it and letting me know if it is back in a working state? Sorry for the inconvenience. Felix

**Comment by Lanilen** [comment]
Hi Felix,

Awesome, I tried the latest and it works like a charm. Thanks a lot!

**Comment by FelixKrueger** [comment]
Perfect, thanks for the feedback. Sounds like we need a new, small release...
