### ISSUE TITLE
Trimgalore error

### ISSUE THREAD

**Issue by DiegoZavallo** [FelixKrueger/TrimGalore#57]
Hi Felix, I'm trying to run trimgalore on some RRBS data, but I'm having problems wiht cutadapt version. I running the data on a server with cutadapt 1.9.1 version doen't work. 
Since I never have troubles with trimgalore on my own computer, I run a test with the same data and start runnnin perfectly. 
The only difference that I see is the cutadapt versions. On my computer I have 1.14 cutadapt version, while on the server I updated to 1.9.1
Both trimgalore version are 0.6.1

Here are the run and the output on both computers:
Server:

`trim_galore -q 30 --phred33 --fastqc --illumina --rrbs --gzip Agrelo_10A1_sar073_L002.fastq.gz Agrelo_10A1_sar073_L002.fastq.gz Agrelo_10A1_sar073_L003.fastq.gz Agrelo_10A1_sar073_L004.fastq.gz Agrelo_10A4_sar074_L001.fastq.gz Agrelo_10A4_sar074_L002.fastq.gz Agrelo_10A4_sar074_L003.fastq.gz Agrelo_10A4_sar074_L004.fastq.gz Agrelo_10A7_sar075_L001.fastq.gz Agrelo_10A7_sar075_L002.fastq.gz Agrelo_10A7_sar075_L003.fastq.gz Agrelo_10A7_sar075_L004.fastq.gz Gualtallary_10G3_sar076_L001.fastq.gz Gualtallary_10G3_sar076_L002.fastq.gz Gualtallary_10G3_sar076_L003.fastq.gz Gualtallary_10G3_sar076_L004.fastq.gz Gualtallary_10G7_sar077_L001.fastq.gz Gualtallary_10G7_sar077_L002.fastq.gz Gualtallary_10G7_sar077_L003.fastq.gz Gualtallary_10G7_sar077_L004.fastq.gz Gualtallary_10G9_sar078_L001.fastq.gz Gualtallary_10G9_sar078_L002.fastq.gz Gualtallary_10G9_sar078_L003.fastq.gz Gualtallary_10G9_sar078_L004.fastq.gz -o ../Trim_galore`

> Multicore support not enabled. Proceeding with single-core trimming.
> Path to Cutadapt set as: 'cutadapt' (default)
> Cutadapt seems to be working fine (tested command 'cutadapt --version')
> Output will be written into the directory: /home/dzavallo/RRBS/Vid/Trim_galore/
> Writing report to '/home/dzavallo/RRBS/Vid/Trim_galore/Agrelo_10A1_sar073_L002.fastq.gz_trimming_report.txt'
> 
> SUMMARISING RUN PARAMETERS
> ==========================
> Input filename: Agrelo_10A1_sar073_L002.fastq.gz
> Trimming mode: single-end
> Trim Galore version: 0.6.1
> Cutadapt version: 1.9.1
> Number of cores used for trimming: 1
> Quality Phred score cutoff: 30
> Quality encoding type selected: ASCII+33
> Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; user defined)
> Maximum trimming error rate: 0.1 (default)
> Minimum required adapter overlap (stringency): 1 bp
> Minimum required sequence length before a sequence gets removed: 20 bp
> File was specified to be an MspI-digested RRBS sample. Read 1 sequences with adapter contamination will be trimmed a further 2 bp from their 3' end, and Read 2 sequences will be trimmed by 2 bp from their 5' end to remove potential methylation-biased bases from the end-repair reaction
> Running FastQC on the data once trimming has completed
> Output file(s) will be GZIP compressed
> 
> Argument "1.9.1" isn't numeric in numeric lt (<) at /home/dzavallo/software/TrimGalore-0.6.1/trim_galore line 593.
>   >>> Now performing adaptive quality trimming with a Phred-score cutoff of: 30 <<<
> 
> cutadapt version 1.9.1
> Copyright (C) 2010-2015 Marcel Martin <marcel.martin@scilifelab.se>
> 
> cutadapt removes adapter sequences from high-throughput sequencing reads.
> 
> Usage:
>     cutadapt -a ADAPTER [options] [-o output.fastq] input.fastq
> 
> For paired-end reads:
>     cutadapt -a ADAPT1 -A ADAPT2 [options] -o out1.fastq -p out2.fastq in1.fastq in2.fastq
> 
> Replace "ADAPTER" with the actual sequence of your 3' adapter. IUPAC wildcard
> characters are supported. The reverse complement is *not* automatically
> searched. All reads from input.fastq will be written to output.fastq with the
> adapter sequence removed. Adapter matching is error-tolerant. Multiple adapter
> sequences can be given (use further -a options), but only the best-matching
> adapter will be removed.
> 
> Input may also be in FASTA format. Compressed input and output is supported and
> auto-detected from the file name (.gz, .xz, .bz2). Use the file name '-' for
> standard input/output. Without the -o option, output is sent to standard output.
> 
> Citation:
> 
> Marcel Martin. Cutadapt removes adapter sequences from high-throughput
> sequencing reads. EMBnet.Journal, 17(1):10-12, May 2011.
> http://dx.doi.org/10.14806/ej.17.1.200
> 
> Use "cutadapt --help" to see all command-line options.
> See http://cutadapt.readthedocs.org/ for full documentation.
> 
> cutadapt: error: no such option: -j
> 
>   >>> Quality trimming completed <<<
> 0 sequences processed in total
> 
> Unable to close QUAL filehandle: 
> 

As you see, the only odd thing appears to be related to cutadapt. I try to googled the error and I only found something related to python version.
The python version on the server is: Python 2.7.12, while on my computer is: Python 2.7.13 :: Anaconda custom (64-bit)

Here is the run on my computer with the exact same command:

`trim_galore -q 30 --phred33 --fastqc --illumina --rrbs --gzip Agrelo_10A1_sar073_L002.fastq.gz Agrelo_10A1_sar073_L002.fastq.gz Agrelo_10A1_sar073_L003.fastq.gz Agrelo_10A1_sar073_L004.fastq.gz Agrelo_10A4_sar074_L001.fastq.gz Agrelo_10A4_sar074_L002.fastq.gz Agrelo_10A4_sar074_L003.fastq.gz Agrelo_10A4_sar074_L004.fastq.gz Agrelo_10A7_sar075_L001.fastq.gz Agrelo_10A7_sar075_L002.fastq.gz Agrelo_10A7_sar075_L003.fastq.gz Agrelo_10A7_sar075_L004.fastq.gz Gualtallary_10G3_sar076_L001.fastq.gz Gualtallary_10G3_sar076_L002.fastq.gz Gualtallary_10G3_sar076_L003.fastq.gz Gualtallary_10G3_sar076_L004.fastq.gz Gualtallary_10G7_sar077_L001.fastq.gz Gualtallary_10G7_sar077_L002.fastq.gz Gualtallary_10G7_sar077_L003.fastq.gz Gualtallary_10G7_sar077_L004.fastq.gz Gualtallary_10G9_sar078_L001.fastq.gz Gualtallary_10G9_sar078_L002.fastq.gz Gualtallary_10G9_sar078_L003.fastq.gz Gualtallary_10G9_sar078_L004.fastq.gz -o ../Trim_galore`

> Multicore support not enabled. Proceeding with single-core trimming.
> Path to Cutadapt set as: 'cutadapt' (default)
> Cutadapt seems to be working fine (tested command 'cutadapt --version')
> Output directory ../Trim_galore/ doesn't exist, creating it for you...
> 
> Output will be written into the directory: /media/diego/Diego_externo/Documents/INTA/Methylation/Raw_Data5_epiGBS_NextSeq/Trim_galore/
> Writing report to '/media/diego/Diego_externo/Documents/INTA/Methylation/Raw_Data5_epiGBS_NextSeq/Trim_galore/Agrelo_10A1_sar073_L001.fastq.gz_trimming_report.txt'
> 
> SUMMARISING RUN PARAMETERS
> ==========================
> Input filename: Agrelo_10A1_sar073_L001.fastq.gz
> Trimming mode: single-end
> Trim Galore version: 0.6.1
> Cutadapt version: 1.14
> Number of cores used for trimming: 1
> Quality Phred score cutoff: 30
> Quality encoding type selected: ASCII+33
> Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; user defined)
> Maximum trimming error rate: 0.1 (default)
> Minimum required adapter overlap (stringency): 1 bp
> Minimum required sequence length before a sequence gets removed: 20 bp
> File was specified to be an MspI-digested RRBS sample. Read 1 sequences with adapter contamination will be trimmed a further 2 bp from their 3' end, and Read 2 sequences will be trimmed by 2 bp from their 5' end to remove potential methylation-biased bases from the end-repair reaction
> Running FastQC on the data once trimming has completed
> Output file(s) will be GZIP compressed
> 
> Your version of Cutadapt is fairly old (detected v1.14), please consider updating Cutadapt!
>   >>> Now performing adaptive quality trimming with a Phred-score cutoff of: 30 <<<
> 
> This is cutadapt 1.14 with Python 2.7.13
> Command line parameters: -e 0.1 -q 30 -a X Agrelo_10A1_sar073_L001.fastq.gz
> Trimming 1 adapter with at most 10.0% errors in single-end mode ...
> Finished in 7.05 s (7 us/read; 8.28 M reads/minute).
> 
> === Summary ===
> 
> Total reads processed:                 972,939
> Reads with adapters:                         0 (0.0%)
> Reads written (passing filters):       972,939 (100.0%)
> 
> Total basepairs processed:    72,943,190 bp
> Quality-trimmed:               1,684,485 bp (2.3%)
> Total written (filtered):     71,258,705 bp (97.7%)
> 
> === Adapter 1 ===
> 
> Sequence: X; Type: regular 3'; Length: 1; Trimmed: 0 times.
> 
> 
>   >>> Quality trimming completed <<<
> 972939 sequences processed in total
> 
> Writing final adapter and quality trimmed output to Agrelo_10A1_sar073_L001_trimmed.fq.gz
> 
> 
>   >>> Now performing adapter trimming for the adapter sequence: 'AGATCGGAAGAGC' from file Agrelo_10A1_sar073_L001.fastq.gz_qual_trimmed.fastq <<< 
> 

I kill the process before it finished, but as you can see it ran just fine.

Could you give a hint on this? I have to make the analysis on the server due to the amount of data y processing capacity.

Thanks

Best

Diego

**Comment by FelixKrueger** [comment]
Hi Diego,

Could you try to download or clone the latest development version of Trim Galore? I think I might have fixed this issue already. LEt me know if if still doen't work with version `0.6.1_dev`.

Cheers, Felix

**Comment by DiegoZavallo** [comment]
Felix, I think I have it installed:

`$ trim_galore --version`

              

> Quality-/Adapter-/RRBS-/Speciality-Trimming
>                                 [powered by Cutadapt]
>                                        version 0.6.1
> 
>                                 Last update: 20 03 2019
> 

or the `_dev`  part is newer?

**Comment by FelixKrueger** [comment]
Yes, the dev version is newer.

`git clone https://github.com/FelixKrueger/TrimGalore.git` should do the trick

**Comment by DiegoZavallo** [comment]
Felix, you were right! I updated trimgalore and now is running. Although I'm having trouble updating cutadapt from 1.9.1 to 1.14. Are there big differences?

**Comment by FelixKrueger** [comment]
You would have to look this up on the Cutadapt change log, but I suppose for what you are doing here it won't make much of a difference. I'm glad it is now working!
