### ISSUE TITLE
--illumina default adapter trimming

### ISSUE THREAD

**Issue by pvphaneuf** [FelixKrueger/TrimGalore#6]
In the user guide, the **Full list of options for Trim galore!** documentation describes illumina's default adapter as GATCGGAAGAGC, which seems to be missing an initial 'A'  in comparison to the default illumina adapter sequence described within the **Adaptive quality and adapter trimming with Trim Galore!** section.

**Comment by FelixKrueger** [comment]
Thanks for spotting this, I have now fixed this.
