### ISSUE TITLE
What do these output files mean?

### ISSUE THREAD

**Issue by JavisPeng** [FelixKrueger/TrimGalore#60]
This is my first time using this software, and I went to know what do these output files mean?
command:
`trim_galore --paired --phred33 --fastqc --gzip -o clean_fq fq_data/N1_1.fq.gz  fq_data/N1_2.fq.gz`
output files:
```
 N1_1_trimmed.fq.gz
 N1_2_trimmed.fq.gz
 N1_1_val_1.fq.gz
 N1_2_val_2.fq.gz
```
Specially, what  *_trimmed.fq.gz and *_val_1.fq.gz stand for ?  which file can I use in the sequence alignment stage ?

**Comment by FelixKrueger** [comment]
**Single-end**
The `*_trimmed.fq.gz` are the final output of single-end trimming.

**Paired-end**
The `*_trimmed.fq.gz` are produced as intermediate output (as R1 and R2 are trimmed individually in the first instance). Once the trimming has completed, Trim Galore will launch a round of 'validation' (which is is where the files get the `val` in their names from), which primarily performs length-cutoff filtering (and a few more optional things I believe). Once the validation is complete, the `trimmed` files will be deleted, and you are left with only the files `N1_1_val_1.fq.gz and
 N1_2_val_2.fq.gz`.

**Comment by bongoholmk** [comment]
Just to let you know I contacted the HPC people to take a look. Apparently the  jobs timed out as I did not give it enough time in the queue (it timed out after 7 hours). So I am running it again.  Fingers crossed.

Thanks for your help!
Karen


Karen Holm, DVM
Wildlife Conservation Center
Arrington, VA 22922
***@***.***
