### ISSUE TITLE
Question about Illumina adapter removal

### ISSUE THREAD

**Issue by HilaryGenetics** [FelixKrueger/TrimGalore#61]
Hello. 
I recently started exploring CutAdapt documentation, and found a user guide indicating that the "AGATCGGAAGAGC " adapter sequence should not be used due to its occurrence in the human genome (https://cutadapt.readthedocs.io/en/stable/guide.html). Does this mean that I need to specify my own full length illumina adapters if I am trying to trim adapters/indices from a TruSeq Illumina run of humans? 
In the Update TrimGalore User Guide md file, it states the following: "The auto-detection behaviour can be overruled by specifying an adapter sequence manually or by using `--illumina`, `--nextera` or `--small_rna`. **Please note**: the first 13 bp of the standard Illumina paired-end adapters (`AGATCGGAAGAGC`) recognise and removes ..." This makes me think that perhaps Trimgalore still uses this sequence?
My apologies if there is an update I failed to found that already addresses this issue.
Thank you for your time.

**Comment by FelixKrueger** [comment]
Hi @HilaryGenetics ,

I just had a quick look, and the 13-mer used to detect and remove does indeed occur naturally in the human genome, more specifically at these 12 positions: 

 ```
bowtie -n 0 -l 13 --all -f -S /bi/scratch/Genomes/Human/GRCh38/Homo_sapiens.GRCh38 adapter_sequence.fa
@HD     VN:1.0  SO:unsorted
...
@PG     ID:Bowtie       VN:1.2.2        CL:"/bi/apps/bowtie/1.2.2/bowtie-align-s --wrapper basic-0 -n 0 -l 13 --all -f -S /bi/scratch/Genomes/Human/GRCh38/Homo_sapiens.GRCh38 adapter_sequence.fa"
Adapter 0       5       64690510        255     13M     *       0       0       AGATCGGAAGAGC   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 0       11      114779487       255     13M     *       0       0       AGATCGGAAGAGC   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 0       3       48254550        255     13M     *       0       0       AGATCGGAAGAGC   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 0       19      30548315        255     13M     *       0       0       AGATCGGAAGAGC   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 0       13      56182421        255     13M     *       0       0       AGATCGGAAGAGC   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 0       15      38727103        255     13M     *       0       0       AGATCGGAAGAGC   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 16      1       221146506       255     13M     *       0       0       GCTCTTCCGATCT   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 16      4       42732697        255     13M     *       0       0       GCTCTTCCGATCT   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 16      12      93854159        255     13M     *       0       0       GCTCTTCCGATCT   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 16      6       92574416        255     13M     *       0       0       GCTCTTCCGATCT   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 16      6       4493956 255     13M     *       0       0       GCTCTTCCGATCT   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
Adapter 16      5       149867216       255     13M     *       0       0       GCTCTTCCGATCT   IIIIIIIIIIIII   XA:i:0  MD:Z:13 NM:i:0  XM:i:13
```

So yes, for default mapping reads in these regions would probably get trimmed at this position (which doesn't necessarily mean that the read won't align anyway). 

Whilst the overall effect on any experiment of choice would probably be negligible, you can of course always choose to use a longer adapter sequence. Then you will, however, have to specify the correct adapters for R1 and R2 since they diverage after position 13. Does that make sense?

**Comment by HilaryGenetics** [comment]
Thank you; this does make sense. If I chose to use a longer adapter, do I only need to specify the Illumina R1/R2 main adapter, or would you also recommend using all of the Index Adapters (i7/i5 for TruSeq)?

**Comment by FelixKrueger** [comment]
To be perfectly honest I personally would not change anything and just use the part of the adapter sequence that is in common for all of the adapters (which is the default).
If you wanted to specify somewhat longer R1 and R2 adapters with `-a` and `-a2` it would probably be OK to stop just before the TruSeq adapter barcode starts. But you would have to consult the product sheets to get the sequence right for this. Good luck! Felix

**Comment by HilaryGenetics** [comment]
Ok; thank you for your insight!
