### ISSUE TITLE
--basename does not work with --output_dir for SE read

### ISSUE THREAD

**Issue by pinetree1** [FelixKrueger/TrimGalore#62]
When --basename and --output_dir are specified for SE fastq, the command did not change the output fastq file to outdir/test_trimmed.fq.gz:

trim_galore --basename test --output_dir outdir indir/s1_R1.fastq.gz 

The two options combined are OK with paired-ends.

**Comment by FelixKrueger** [comment]
Thanks for spotting this. I have just tried to fix it, could you give the development version a go on your end to see if it works now?

**Comment by pinetree1** [comment]
Yes, it works now. Thanks.
