### ISSUE TITLE
Per Base Sequence Content after Adapter Removal

### ISSUE THREAD

**Issue by cazzlewazzle89** [FelixKrueger/TrimGalore#63]
Hi Felix,

Thanks for the great tool. 
I'm still seeing high %A and %T per base sequence content that the beginning of my reads  after removing Nextera adapters. Do you think this is because cutadapt is failing to remove all adapter sequences?

The command I used was:
trim_galore --paired --nextera R1.fastq.gz R2.fastq.gz --fastqc -q 20 --length 105 -j 40 -o trimout

Thankful for any advice you might have,
Calum

![pbsc](https://user-images.githubusercontent.com/23379482/62134471-73fab100-b2d8-11e9-80b1-0caf0291c7da.PNG)

**Comment by FelixKrueger** [comment]
Hi Calum,

The easiest way to check whether the adapter trimming has worked as expected is to look at the FastQC adapter contamination plot. There you should see a line for Nextera coming up, and this should then be gone in the trimmed sample. If your version of FastQC does not show the Nextera sequence by default (which it should), you can add this to the `contaminants.txt` file:

```
Illumina Universal Adapter                                      AGATCGGAAGAG
Illumina Small RNA Adapter                                      ATGGAATTCTCG
Nextera Transposase Sequence                            CTGTCTCTTAT
```

The positional sequence bias at the start has nothing to do with adapter contamination, and has been discussed in blog posts and also a publication, e.g. here: https://sequencing.qcfail.com/articles/positional-sequence-bias-in-random-primed-libraries/

The bias towards the end of the read is a consequence of the adapter trimming process, again nothing to worry about.

Finally, your command looks a bit harsh for my taste. I suppose 

`trim_galore --paired R1.fastq.gz R2.fastq.gz --fastqc -j 40 -o trimout` would be OK. It should find the right adapter sequence automatically, and not remove everything that is shorter than 105 (leave it in of course if you really want this length cut-off.

**Comment by cazzlewazzle89** [comment]
Hi Felix,

Thanks a million for the very prompt and informative response. I keep second guessing myself when it comes to adapters and quality trimming.

All the best and thanks again for a great tool,
Calum

**Comment by FelixKrueger** [comment]
I'm glad it helped, let me know if you've got any further questions.

**Comment by ronin-gw** [comment]
Hi,

I recently noticed that some of the nucleotides at the start positions were biassed when I analyzed CUT&Tag data.
![index](https://user-images.githubusercontent.com/8822840/132005488-0fae465d-7e19-436d-9475-d6260ddcd0f2.png)

[The paper](https://bmcbiotechnol.biomedcentral.com/articles/10.1186/s12896-016-0326-1#Sec9) I found says that Tn5 transposase causes the symmetrical selection bias between base 1 and base 9.
So you may not have to worry about such kind of bias when your data comes from a protocol using transposase like ATAC-seq.

**Comment by amtabonda** [comment]
Hi,

Is anyone here using Fastp in checking the quality of raw reads? I have a problem with the Per base sequence content, especially on the end position of the reads. There is a distinct downfall in the % A of my reads at the end position. I already tried the command for overrepresentation analysis, but it seems that the % A did not improve. Can anyone help me with this? Thanks a lot :)
