### ISSUE TITLE
Error while running Trim_galore

### ISSUE THREAD

**Issue by huangxingnan1994** [FelixKrueger/TrimGalore#65]
Hi there,
I have a problem about running trim_galore. When trim_galore ran, it always reported an error as follows:
SUMMARISING RUN PARAMETERS
==========================
Input filename: ./YSY-05-2_L3_Q805602.R1.fastq.gz
Trimming mode: paired-end
Trim Galore version: 0.6.1
Cutadapt version: 2.5
Number of cores used for trimming: 1
Quality Phred score cutoff: 20
Quality encoding type selected: ASCII+33
Adapter sequence: 'CTGTCTCTTATA' (Nextera Transposase sequence; user defined)
Maximum trimming error rate: 0.1 (default)
Minimum required adapter overlap (stringency): 1 bp
Minimum required sequence length for both reads before a sequence pair gets removed: 20 bp
Output file will be GZIP compressed

This is cutadapt 2.5 with Python 3.7.3
Command line parameters: -j 1 -e 0.1 -q 20 -O 1 -a CTGTCTCTTATA ./YSY-05-2_L3_Q805602.R1.fastq.gz
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: [Errno 13] Permission denied: 'pigz'

**Comment by FelixKrueger** [comment]
Can you please update to the latest version (0.6.4) and see if the problem is still there?

**Comment by huangxingnan1994** [comment]
Okay, the problem has been solved. Thanks.

**Comment by FelixKrueger** [comment]
Excellent, thanks for the update.

**Comment by huangxingnan1994** [comment]
Hey Felix,
I am sorry that this error appeared again after updating.

**Comment by FelixKrueger** [comment]
So what is the problem again, do you have `pigz` installed, and can you run it? What happens when you run `pigz` on its own?

**Comment by huangxingnan1994** [comment]
The same error appeared againg. I have installed `pigz`, but there is nothing wrong when running `pigz` individually.

**Comment by FelixKrueger** [comment]
Trim Galore should never attempt to run `pigz` if you don't ask for multi-core processing, so I don't really understand the error message to be honest. Can you link the exact command you used, and the on-screen output again?

Also, could you try to run Cutadapt on its own and see what that says?

`cutadapt -j 1 -e 0.1 -q 20 -O 1 -a CTGTCTCTTATA ./YSY-05-2_L3_Q805602.R1.fastq.gz`

**Comment by gevro** [comment]
I am having the same problem.

**Comment by FelixKrueger** [comment]
So you have `pigz` installed, and if run on its own it is working? And you have Cutadapt installed, which on its own is working? 
Have you tried running Cutadapt using a single core, or multiple cores? If not, please try the commands:

Single core: `cutadapt -j 1 -e 0.1 -q 20 file.fastq.gz`
Four cores: `cutadapt -j 4 -e 0.1 -q 20 file.fastq.gz`

**Comment by gevro** [comment]
Not sure how to install pigz. cutadapt -j 1 does not work - still gives the same error. How do I instal pigz? This should be described in the cutadapt installation instructions.

**Comment by FelixKrueger** [comment]
You should be able to install `pigz` like any other software you install on your machine. Here is a linkhttps://zlib.net/pigz/. Can you run the single and four core examples of Cutadapt mentioned two notes earlier?

**Comment by gevro** [comment]
Thanks. pigz is difficult to compile. But I found a pre-built binary and now it works.

**Comment by FelixKrueger** [comment]
Ah perfect.
