### ISSUE TITLE
Inconsistent naming while using --basename

### ISSUE THREAD

**Issue by pblumenkamp** [FelixKrueger/TrimGalore#66]
Hi Felix,

the suffix of each file while using `--basename` differs from the file names when not using a custom file name.

I have used version 0.6.4 (Last update: 31 07 2019) and the following command:
```
trim_galore --paired -o base_out --basename base foo.fastq bar.fastq
```
All files should be named PREFERRED\_NAME\_val\_1.fq and PREFERRED\_NAME\_val\_2.fq but are actually named PREFERRED\_NAME\_R1\_val\_1.fq and PREFERRED\_NAME\_R2\_val\_2.fq.

I have also tested it with and without `-o` and without `--basename`. The "\_RX\_" is only added to the file name if `--basename` is used. This is also only the case for paired-end. In single-end mode the names are all like described in the documentation.

Regards,
Patrick

**Comment by FelixKrueger** [comment]
Hi Patrick,

I have tried to take out the _R1 and _R2 for the `--paired --basename` scenario (here 0f631e5f979281fd4f18faef39818399a068a4b3). Could you try to clone the dev version and see if it works as expected? Cheers, Felix

**Comment by pblumenkamp** [comment]
Now it is working. Thanks!

**Comment by FelixKrueger** [comment]
Excellent, thanks for the quick feedback.
