### ISSUE TITLE
Mistake in the explanation of parameter "--basename <PREFERRED_NAME>"

### ISSUE THREAD

**Issue by zhxiaokang** [FelixKrueger/TrimGalore#67]
When it's paired-end data, it says that the output files will be named PREFERRED_NAME_val_1.fq(.gz) and PREFERRED_NAME_val_2.fq(.gz). But when I used TrimGalore, I found that they were actually named as PREFERRED_NAME_R1_val_1.fq(.gz) and PREFERRED_NAME_R2_val_2.fq(.gz)

**Comment by FelixKrueger** [comment]
I believe this has come up and been fixed already (https://github.com/FelixKrueger/TrimGalore/issues/66). Please clone the latest dev version and see if that works.
