### ISSUE TITLE
Trim Galore exit signal: '512' 

### ISSUE THREAD

**Issue by hailee-s** [FelixKrueger/TrimGalore#68]
I'm trying to trim single end reads using Trim Galore, I have been receiving the following error message 

trim_galore '/home/bobcatgenomics/Desktop/Hailee/Raw Reads/WT3/WT3_S2_R1_001.fastq.gz.1' 
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Path to Cutadapt set as: 'cutadapt' (default)
1.18
Cutadapt seems to be working fine (tested command 'cutadapt --version')

AUTO-DETECTING ADAPTER TYPE
===========================
Attempting to auto-detect adapter type from the first 1 million sequences of the first file (>> /home/bobcatgenomics/Desktop/Hailee/Raw Reads/WT3/WT3_S2_R1_001.fastq.gz.1 <<)

Found perfect matches for the following adapter sequences:
Adapter type	Count	Sequence	Sequences analysed	Percentage
Illumina	0	AGATCGGAAGAGC	298	0.00
Nextera	0	CTGTCTCTTATA	298	0.00
smallRNA	0	TGGAATTCTCGG	298	0.00
Unable to auto-detect most prominent adapter from the first specified file (count Illumina: 0, count Nextera: 0)
Defaulting to Illumina universal adapter ( AGATCGGAAGAGC ). Specify -a SEQUENCE to avoid this behavior).

Writing report to 'WT3_S2_R1_001.fastq.gz.1_trimming_report.txt'

SUMMARISING RUN PARAMETERS
==========================
Input filename: /home/bobcatgenomics/Desktop/Hailee/Raw Reads/WT3/WT3_S2_R1_001.fastq.gz.1
Trimming mode: single-end
Trim Galore version: 0.5.0_dev
Cutadapt version: 1.18
Quality Phred score cutoff: 20
Quality encoding type selected: ASCII+33
Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; default (inconclusive auto-detection))
Maximum trimming error rate: 0.1 (default)
Minimum required adapter overlap (stringency): 1 bp
Minimum required sequence length before a sequence gets removed: 20 bp

Writing final adapter and quality trimmed output to WT3_S2_R1_001.fastq.gz.1_trimmed.fq

  >>> Now performing quality (cutoff '-q 20') and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file /home/bobcatgenomics/Desktop/Hailee/Raw Reads/WT3/WT3_S2_R1_001.fastq.gz.1 <<< 
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: If a pair of .fasta and .qual files is given, the -f/--format parameter cannot be used.

Cutadapt terminated with exit signal: '512'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

**Comment by FelixKrueger** [comment]
Hi @hailee-s 

Could you please:
a) update Trim Galore to v0.6.5, and
b) if the error is still there, provide the entire command you are using to call it.

Cheers, Felix

**Comment by FelixKrueger** [comment]
Haven't heard back from this, so I assume it is now all working.
