### ISSUE TITLE
clipping before or after adapter trimming

### ISSUE THREAD

**Issue by KerstenBreuer** [FelixKrueger/TrimGalore#70]
Hi,

I would like to know whether clipping (--clip_R1/--clip_R2/...) occurs before or after adapter trimming?

I am processing Accel-seq data , and they [advise ](https://www.genetargetsolutions.com.au/wp-content/uploads/2015/05/Accel-NGS%c2%ae-1S-Plus-Methyl-Seq-Tail-Trimming-For-Better-Data-1.pdf) to clip 15 bp from each read after adapter trimming.

Thanks a lot for your help,
Kersten

**Comment by FelixKrueger** [comment]
Hi Kersten,

The clipping occurs *after* the trimming is complete, so the order is:
`quality trimming  > adapter trimming > manual clippling` 

Even though this is arguably not so relevant for 5' clipping as the other trimming occurs on the 3' end. Hope this helps.

**Comment by KerstenBreuer** [comment]
OK perfect. So it is in line with swifts recommendations.

Thank you
