### ISSUE TITLE
Allowed values for adapter vs adapter2?

### ISSUE THREAD

**Issue by al-dunstan** [FelixKrueger/TrimGalore#72]
process_commandline() checks the values of $adapter and $adapter2.  At line 2505 $adapter can be /^[ACTGNXactgnx]+$/, but at line 2537 $adapter2 can only be /^[ACTGNactgn]+$/ (X is not allowed).  Should [xX] be allowed for both of them?

**Comment by FelixKrueger** [comment]
I suppose that could be arranged. However, the reason why `X` was allowed in the first place was to allow quality trimming only, by supplying a base that does not exist (`-a X`). Do you have a reason why you would need to use `X` for `-a 2`?

**Comment by al-dunstan** [comment]
No.  I was just looking at the code & saw that they were different and thought 'hmmmmm.......'.

**Comment by FelixKrueger** [comment]
That's fine then, a perfectly valid pastime find :). Let's keep it as it is for the time being then, shall we? Cheers, Felix

**Comment by al-dunstan** [comment]
Works for me!  Thanks for the quick reply.
