### ISSUE TITLE
polyA option

### ISSUE THREAD

**Issue by xiaoyunguo** [FelixKrueger/TrimGalore#74]
Hi Felix,

First, thank you very much for your prompt reply to my previous question on Bismark. It helped to clear up things.

There is a polyA option in trim_galore that allows to trim off polyA at the 3' end of read1 and polyT at the 5' end of read2 (paired end). I wonder why this option? Are the polyA coming from the adapter?

The reason I asked is that I am seeing in my data (RRBS, paired end, bulk sequencing) that > 90% of reads (only counting unique reads) in read2 have A or polyA at the 5' end, which is opposite to what is suggested in the polyA option of trim_galore. I am wondering why. Is there a way to use trim_galore to trim the As off?  The number of As varies. 

Additional info about my data: >90% of reads (only counting unique reads) in read1 start with CGG/TGG at the 5' end, as expected. But the mapping ratio is 60-70% (default Bismark stringency setting, bowtie2 end to end), which doesn't seem too bad comparing with the limited amount of other RRBS data that I've seen. Or is my standard too low?

I know this is not exactly a trim_galore issue, but would greatly appreciate if you can help. 

Thanks

Xiaoyun

**Comment by FelixKrueger** [comment]
Dear Xiaoyun,

The polyA trimming option was really designed to deal with data coming from a (at the time experimental) poly-A library preparation method developed by Fisher Scientific (Collibri kit). It is intended to be used for RNA-seq data to analyse alternative poly-adenylation, and as such should **not** be used for RRBS data.

```
>90% of reads in read1 start with CGG/TGG at the 5' end, as expected.
```
That sounds great.
```
Mapping ratio is 60-70%.
```
This is also not bad, but depends a little on read length. I assume you trimmed the data with the Trim Galore option `--rrbs`?

For Read 2 it is perfectly normal to start with an A, as it is the reverse complement of a C in non-CG context from R1. Imagine the end of a fragment:

```
CCGG - 3'
GGCC - 5'
```
Then after end-repair and fill in the read would look like this:

```
CCG - 3'
GGC - 5'
```
Where second position (the C in CG context) tends to carry an artificial unmethylated status. After trimming with Trim Galore Read 1 has 2bp from the end removed, while Read 2 gets 2bp trimmed from the start, resulting in the following end of a fragment after trimming:

```
C - 3'
G - 5'
```
Now if the C on the top strand was unmethylated, and there is a 99% + chance that it was unmethylated as it is in non-CG context, the C on the top strand would become an A after bisulfite conversion. This in turn means that almost all Read 2 have to start with one (or potentially more) A.

Does this make sense?

**Comment by xiaoyunguo** [comment]
Wow, Thank you so much for the prompt reply.

Yes, I forgot the fact that trimming in rrbs mode will trim off the 2bp in
read2, plus the bisulfite conversion!

Thank you again!

Best

Xiaoyun

**Comment by FelixKrueger** [comment]
Excellent, I am assuming it's all working then.
