### ISSUE TITLE
more details about -e : Maximum allowed error rate

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/TrimGalore#77]
Dear Felix, 

Can you provide more description to `-e` : Maximum allowed error rate. It will be great if you can show an example. 

Maximum allowed error rate (no. of errors divided by the length of the matching region)

Thanks. 

Shicheng

**Comment by FelixKrueger** [comment]
Let's assume Trim Galore auto-detected the adapter to be the Illumina standard adapter, it will use the sequence `AGATCGGAAGAGC`. With this sequence being 13 bp long, and the default error rate set to `-e 0.1` (read: 10% error are tolerated), this would allow a maximum number of 

`13bp * 0.1 = 1bp` (rounded down)

So in words this would mean that in its default mode, Trim Galore attempts to find the Illumina adapter by looking for the sequence above, tolerating a maximum mismatch of 1bp in the sequence. Anything above that threshold is not considered adapter contamination.

Makes sense?

**Comment by Shicheng-Guo** [comment]
Dear Felix, 

I think it does make sense. what I am thinking is what the bad situation it will be if I set -e 0.2 or 0.3 in my command? do you have any expectations since in my case only -e 0.2 or 0.3 will remove all the Illumina TruSeq Adapter, Index 22

Thanks. 

Shicheng

**Comment by FelixKrueger** [comment]
In my mind, setting `-e 0.2` or `-e 0.3` is not a good idea, as for the default Illumina sequence this will allow 2-3bp, or 3-4bp mismatches in a sequences as short as 13bp (not exactly sure about the rounding behaviour but you could test this easily enough if you are interested). This will start to target and remove an awful lot of sequences that are just regular genomic sequences, but with 4 mismatches look similar enough to the start of the adapter. So in other words, this will result in a serious loss of data.
 
If you select a longer sequence, e.g. the entire TruSeq Index 22 sequence, it will be a similar problem, and I believe you would need to specify different adapters for Read 1 and Read 2 for paired-end reads.

The best test for whether adapter contamination removal works, is the following:

Run `FastQC` on your data and look at the plot for `Adapter Contamination`. If you have read-through contamination, there will be a cumulative curve for the `Illumina standard adapter` (TruSeq falls into this category).

Then take our file and run:

```
trim_galore --fastqc file.fastq.gz
``` 

This should auto-detect Illumina adapters, and remove them. If you then check the same adapter contamination plot in FastQC for the trimmed file again, the line for `Illumina Standard adapter` will have disappeared (I am willing to bet a fair amount of money on this fact). This means that all (read-through) adapter contamination will have been removed. 
If you still find traces of a the TruSeq Index 22 adapter (e.g. in the Overrepresented Sequences section), it will be some kind of derivative of adapter dimer or the like (e.g. starting with GATC...), but **not** adapter contamination you should worry/care about (I have tried to explain this also in https://github.com/FelixKrueger/TrimGalore/issues/76).

If you think this simple procedure is not sufficient, please attach your command and FastQC profiles (or email them if that's more convenient).
Cheers, Felix

**Comment by Shicheng-Guo** [comment]
Dear Felix, 

Can you give me some suggestion how to deal with this fastq trimming problems? there are some adaptors which are always there. 
```
fastq-dump --gzip SRR10838765
trim_galore --fastqc SRR10838765.fastq.gz
```
Thanks. 
Shicheng

**Comment by FelixKrueger** [comment]
Right. I am afraid this is not really a 'trimming problem', at first glance this library looks like pretty much complete tosh.

As I suspected the library contains a LOT of adapter dimers, looking at the sequence composition plot this is in the region of 50-60% of the whole library, with the Index 3 sequence coming up as the top hit:

```
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGAGGTGTATCTCGTAT | 1617027 | 33.54911325593169 | TruSeq Adapter, Index 3 (97% over 38bp)
-- | -- | -- | --
```

As explained above, these sequences do not get trimmed by default as they are lacking the first `A`. But as they won't align you can just ignore them.

Secondly, there are some ~35% of sequences that start to have read through adapter contamination at base 70 or so. This get successfully identified and removed from the library, but I am not sure what this was. The mapping in FastQ Screen said there might some 1-2% of sequences of human origin in there, but overall this is a pretty spectacular example of a sequencing library gone wrong. There might be indications in there somewhere in the library to tell you whether there is anything useful at all, but chances are that you should just forget about analysing these results. [Sorry for being so harsh]

**Comment by Shicheng-Guo** [comment]
Hi Felix,

the library is built for a certain special case which is not only for human data. that's why it looks weird. However, I agree with you I think the library has something wrong. 

When you mention the adaptors are not removed since they are lacking the first `A`.  That's why I ask can we use -e 0.2 or 0.3 since higher e will remove them. 

Best, 

Shicheng

**Comment by FelixKrueger** [comment]
Just as a theoretical exercise, you can remove these sequences in a number of different ways.

1. If you use the default read-through contamination, you would have the following situation:

```
GATCGGAAGAGC Read
mmmmmMmMmmmm
AGATCGGAAGAGC adapter sequence to be removed.
````

where `m` is a mismatch, and `M` is a match. If you increase the error rate so much that the adapter sequence finds a matching part somewhere in your sequence, then it will trim. This however certainly doesn't mean that you should be doing that, as you will start to trim an awful lot of sequence that isn't adapter at all.

2. If you wanted to use an adapter trimmer for it, it might be easiest to use the adapter sequence without the A from A-tailing: `-a GATCGGAAGAGC`.

3. `grep` would most likely work as well, with a command like `grep -v -B 1 -A 2 ^GATCGGAA`

Following steps 2 and 3, you would still require the normal (= read through) adapter trimming as well.

And finally, as I have mentioned before, I don't think trimming or removing these sequences will have any noticeable effect on the final result of your experiment, as fully-fletched adapter sequences from start to end are so artificial that they will not align to any genome.

**Comment by Shicheng-Guo** [comment]
Awesome. it is exactly what I need. thank you so much for this great approach. 

Best, 

Shicheng

**Comment by FelixKrueger** [comment]
Excellent, glad it helped!
