### ISSUE TITLE
TrimGalore only detects python 2, but I have python 3

### ISSUE THREAD

**Issue by ejwright39** [FelixKrueger/TrimGalore#78]
I suppose this isn't an issue with TrimGalore per se, but I'm running Ubuntu 18.04 (Linux kernel 5.0) and I have python 2.7 on my system specifically for conda and conda envs for programs that require python 2. I also have python 3.6 for everything that requires python 3. By default when I enter "python --version" I get "Python 2.7". As such when I start trim_galore it says multicore support disabled. I assume this is because it does the same "python --version" check. How do I change my default python version in my PATH? I've read that this can cause serious issues though? Or perhaps how do I tell TrimGalore to look for "python3 --version" rather than just "python --version"?

**Comment by FelixKrueger** [comment]
This Python 2 vs 3 discrepancy is just one of a kind, I will be happy to see the back of it some day...

Couldn't you try to open Trim Galore in a text editor, look for `python` commands and mannually change them to `python3`? Let me see how it goes.

**Comment by ejwright39** [comment]
Yes it really is a pain. I actually just did that. It still says multicore support not enabled. Is cutadapt also checking python --version? Not sure if trim_galore is requesting anything from cutadapt?

**Comment by FelixKrueger** [comment]
That might well be... Could you also edit the first line of Cutadapt itself to point to `#!/usr/bin/env python3` ? I am fairly new to the Python field, so maybe some googling might help if this fails?

**Comment by ejwright39** [comment]
Tried that too. Still says Multicore support not enabled. Not a huge deal. The various versions and installations of python are a mess on my system. It's probably some crazy eccentricity of my personal setup more than an issue with TrimGalore.

**Comment by FelixKrueger** [comment]
Excellent, I am glad you got it to work on your slightly eccentric system eventually!
