### ISSUE TITLE
v0.6.5 release tar ball contains v 0.6.4 dev 

### ISSUE THREAD

**Issue by jjv5** [FelixKrueger/TrimGalore#80]
Download of 0.6.5.tar.gz uncompresses to dir named TrimGalore-0.6.5, but the trim_galore program is version 0.6.4_dev:

`grep 0.6 ./trim_galore 
my $trimmer_version = '0.6.4_dev';`

`./trim_galore --version

                        Quality-/Adapter-/RRBS-/Speciality-Trimming
                                [powered by Cutadapt]
                                  version 0.6.4_dev

                               Last update: 24 09 2019`

**Comment by FelixKrueger** [comment]
That's an oversight, sorry. The version and date is now up-to-date in the development branch. Feel free to correct it to 0.6.5 manually if it causes any issues :) See 70bd7626c0518879e06903870aee5363a0dbcff1
