### ISSUE TITLE
Error during unning trim_galore

### ISSUE THREAD

**Issue by krunal2406** [FelixKrueger/TrimGalore#84]
I am trying to run Trim_galore but it is not executing fastQC and i am unable to understand the reason, please find below the output :

/Krunal/chipSeq/jatropa/FastQC/TrimGalore-0.6.5$ trim_galore --fastqc --illumina --paired --retain_unpaired SRR1560724_2.fastq_trimming_report.txt SRR1560724_1.fastq_trimming_report.txt
Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 1.15
single-core operation.
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Writing report to 'SRR1560724_2.fastq_trimming_report.txt_trimming_report.txt'

SUMMARISING RUN PARAMETERS
==========================
Input filename: SRR1560724_2.fastq_trimming_report.txt
Trimming mode: paired-end
Trim Galore version: 0.6.4_dev
Cutadapt version: 1.15
Number of cores used for trimming: 1
Quality Phred score cutoff: 20
Quality encoding type selected: ASCII+33
Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; user defined)
Maximum trimming error rate: 0.1 (default)
Minimum required adapter overlap (stringency): 1 bp
Minimum required sequence length for both reads before a sequence pair gets removed: 20 bp
Length cut-off for read 1: 35 bp (default)
Length cut-off for read 2: 35 bb (default)
Running FastQC on the data once trimming has completed

Cutadapt seems to be reasonably up-to-date. Setting -j 1
Writing final adapter and quality trimmed output to SRR1560724_2.fastq_trimming_report.txt_trimmed.fq

  >>> Now performing quality (cutoff '-q 20') and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file SRR1560724_2.fastq_trimming_report.txt <<< 
Traceback (most recent call last):
  File "/usr/bin/cutadapt", line 11, in <module>
    load_entry_point('cutadapt==1.15', 'console_scripts', 'cutadapt')()
  File "/usr/lib/python3/dist-packages/cutadapt/__main__.py", line 717, in main
    fileformat=options.format, interleaved=is_interleaved_input)
  File "/usr/lib/python3/dist-packages/cutadapt/pipeline.py", line 97, in set_input
    interleaved, mode='r')
  File "/usr/lib/python3/dist-packages/cutadapt/seqio.py", line 698, in open
    mode=mode, qualities=qualities)
  File "/usr/lib/python3/dist-packages/cutadapt/seqio.py", line 768, in _seqopen1
    first_line = file.readline()
AttributeError: 'str' object has no attribute 'readline'

Cutadapt terminated with exit signal: '256'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

Thanks
Krunal

**Comment by FelixKrueger** [comment]
Hi Krunal,

```
trim_galore SRR1560724_2.fastq_trimming_report.txt SRR1560724_1.fastq_trimming_report.txt
```

The command line you linked seems to indicate that you didn't feed the programme FastQ files but some kind of trimming report as input. Could you check this and use `SRR1560724_1.fastq.gz` and `SRR1560724_2.fastq.gz`?

**Comment by krunal2406** [comment]
HI Felix,

Thanks i tried with my fasta previously but it dint worked, i reinstalled Fastqc manually and as you suggested i use zip file and it worked.

Thanks
