### ISSUE TITLE
Error related to cutadapt version 2.5

### ISSUE THREAD

**Issue by xie186** [FelixKrueger/TrimGalore#85]
Hi,

I'm using `TrimGalore 0.6.4` and cutadapt 2.5.  I was given the error shown as below:

```
Use of uninitialized value $major_version in numeric eq (==) at /group/bioinfo/apps/apps/TrimGalore-0.6.4/trim_galore line 615.
Use of uninitialized value $major_version in numeric gt (>) at /group/bioinfo/apps/apps/TrimGalore-0.6.4/trim_galore line 632.
Cutadapt major version was not 1 or higher. Simply too old...
[Thu Mar 26 13:55:48 2020]
Error in rule trimPE:
    jobid: 0
    output: output/trim_galore/3I0/, output/trim_galore/3I0.log, output/trim_galore/3I0/3I0_val_1.fq.gz, output/trim_galore/3I0/3I0_val_2.fq.gz
```

It seems that the reason is that `cutadapt --version` doesn't output the version information to STDERR instead of STDOUT for v2.5. I checked the latest version of TrimGalore: 

https://github.com/FelixKrueger/TrimGalore/blob/beca8023b5bedf5a746b4c492cb0a61f5d2a9dde/trim_galore#L2311

Here we may need to use: 
```
$cutadapt_version = `$path_to_cutadapt --version 2>&1`;
``` 

Thanks,
Shaojun

**Comment by FelixKrueger** [comment]
Thanks for that, could you try the current development version to see if it now works? Cheers, Felix

**Comment by xie186** [comment]
I can successfully run it with the development version. Thank you so much for your quick response. 
Best,
Shaojun

**Comment by FelixKrueger** [comment]
Excellent, thanks for the quick feedback!
