### ISSUE TITLE
fastqc after trimming

### ISSUE THREAD

**Issue by yeroslaviz** [FelixKrueger/TrimGalore#87]
I was wondering if the `fastqc` during `trim_glore` is done after only the quality trimming, or also after the adapter removal.

I ask this because the fastqc results i have doesn't differ much from the original run in respect to the `per base sequence content` In the image below, the left hand side is from the trimmed file, the right one is from the original file.

![image](https://user-images.githubusercontent.com/8927555/79221634-7ac15800-7e56-11ea-9ca8-a98be92ccfd7.png)

Can there be a different explanation to this distribution of bases at the beginning of the reads, if not due to adapter leftovers?

thanks

**Comment by FelixKrueger** [comment]
The FastQC step is indeed performed after both quality and adapter trimming have completed.

The weird stuff you are seeing at the 5' end in most likely not adapter contamination, or at least not the 3'-end read through adapter contamination that Trim Galore is looking for. It much more resembles the sequence bias of random priming at the start of RNA-seq libraries, please read this blog post and the articles cited therein: https://sequencing.qcfail.com/articles/positional-sequence-bias-in-random-primed-libraries/
