### ISSUE TITLE
--three_prime_clip_R1 max=99?

### ISSUE THREAD

**Issue by deanpettinga** [FelixKrueger/TrimGalore#89]
Hi Felix, 

I'm working on a project that necessitates clipping 2x151nt reads down to 2x50nt. I've noticed that when i provide any value longer than 99 for `--three_prime_clip_R1` or `--three_prime_clip_R2`  i get an error:

> [dean]$ trim_galore --paired --three_prime_clip_R1 100 --three_prime_clip_R2 100 raw_data/test-R1.fastq.gz raw_data/test-R2.fastq.gz
\
Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)
The 3' clipping value for read 1 should have a sensible value (> 0 and < read length)

The error message suggests that the user is able to provide any value less than the read length, but the source code below shows a hard-coded max value of `100`. 

> ### Trimming at the 3' end
>   if (defined $three_prime_clip_r1){ # trimming 3' bases of read 1
>       unless ($three_prime_clip_r1 > 0 and $three_prime_clip_r1 < 100){
>       die "The 3' clipping value for read 1 should have a sensible value (> 0 and < read length)\n\n";
>       }
>   }

I recognize that clipping 100nt from illumina reads is uncommon, especially since illumina reads have historically been shorter than 100nt (which could explain the hard-limit). Is there a good reason for this max value that i'm not aware of? would it be possible to increase the allowable clipping length?

cheers,
Dean

PS- thanks so much for this tool! i use it _all_ the time :)

**Comment by FelixKrueger** [comment]
Hi Dean,

Thanks for the nice words. In theory you could of course just edit the 100 out and put 1000 in, it as really just a measure to prevent people from doing silly things...

But I think you should probably use the following option instead:

```
--hardtrim5 <int>       Instead of performing adapter-/quality trimming, this option will simply hard-trim sequences
                        to <int> bp at the 5'-end. Once hard-trimming of files is complete, Trim Galore will exit.
                        Hard-trimmed output files will end in .<int>_5prime.fq(.gz). Here is an example:

                        before:         CCTAAGGAAACAAGTACACTCCACACATGCATAAAGGAAATCAAATGTTATTTTTAAGAAAATGGAAAAT
                        --hardtrim5 20: CCTAA

GGAAACAAGTACACT
```


So

```
trim_galore --hardtrim5 50 *fastq.gz
```

Should do what you need.

**Comment by deanpettinga** [comment]
yes, on further reading, i think your suggested method is indeed what i want.

cheers,
Dean
