### ISSUE TITLE
size of output files

### ISSUE THREAD

**Issue by valentinaOpazo** [FelixKrueger/TrimGalore#92]
Hi, im new in Trim galore. Im using a paired end RRBS data, and the output files (*val_1.fg/*val_2.fq) has different size, What could be wrong? The command used was: 

trim_galore --rrbs --paired --clip_R1 6 --clip_R2 6 -q 28 --length 35 -e 0.02 --fastqc -o $output_path $input_path/SRR2479444_1.fastq $input_path/SRR2479444_2.fastq

**Comment by FelixKrueger** [comment]
Hi @valentinaOpazo 

When you say a different size, do you mean a different file size, or reads of different length? The file size does not necessarily have to be the same, but the output reads should have the same number of reads (and lines).

To test this you could run:

```
wc -l SRR2479444_1.fastq 
wc -l SRR2479444_2.fastq
```

If they do not have the same number of lines, your input is somehow truncated. I thought Trim Galore was checking if the number of reads was different between R1 and R2, and it should die if it finds a discrepancy. Which version are you using?
 
Also, you mentioned that you are new the program, so may I ask why you modify almost every possible parameter? :P In the first place I would run: Also, Trim Galore accepts compressed files in `.gz`, so `gzip *fastq` would reduce the amount of disk space the files require to roughly 10-20%. 

```
trim_galore --rrbs --gzip --paired--fastqc SRR2479444_1.fastq SRR2479444_2.fastq
```

You should certainly not clip away the first 6bp of each read, as you will lose quite a lot of methylation information. Using an error model of 0.5% errors will not allow any errors in an adapter that is only 13bp long (0.5% of 13 is 0.065 errors, which rounds to 0). `-q` and `--length` are a matter of taste, but we personally always use the defaults (20 and 20, respectively).

Let me know how you get on.

**Comment by valentinaOpazo** [comment]
Thank you so much for the answer! In fact, the different size was only for output files (not readings of different length).
On the other hand, I am using public data and the "Per Base Sequence Content" graph obtained by fastQC shows a stronger representation (~ 90%) of some base in the first 6 bps, so I considered correct to remove it. I'm wrong?
For the other parameters I will take into account your recommendation

**Comment by FelixKrueger** [comment]
For some more information about RRBS you can take a look here: https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/RRBS_Guide.pdf, or look at the slides specific for RRBS here: https://www.bioinformatics.babraham.ac.uk/training/Methylation_Course/BS-Seq%20theory%20and%20QC%20lecture.pdf (e.g. slide 22). In short: Yes, you have to expect certain biases, this is exactly what RRBS does.

Good luck with your experiments!
